# Auto-generated by LENS-Craft v1.0
# Source: /Users/fredbook/Code/uCode/programs/repton/src/
# 31 extractors generated


class ReptonLensExtractor:

    def __init__(self, emu):
        """Initialize with a 6502 emulator instance.

        Args:
            emu: Emulator providing read_byte(addr), read_uint16(addr),
                 read_uint32(addr) in little-endian byte order.
        """
        self._emu = emu

    @property
    def src_score_lo(self) -> str:
        """Score (16-bit)"""
        val = self._emu.read_byte(0x900)
        labels = {
        0: "off",
        1: "on"
        }
        return labels.get(val, "unknown")

    @property
    def src_score_hi(self) -> int:
        """SCORE_HI constant"""
        return self._emu.read_byte(0x901)

    @property
    def src_lives(self) -> int:
        """Lives remaining (3-0)"""
        return self._emu.read_byte(0x902)

    @property
    def src_level_num(self) -> int:
        """Current level (1-12)"""
        return self._emu.read_byte(0x903)

    @property
    def src_reptol_state(self) -> str:
        """Reptol status: 0=idle, 1=collecting, 2=ate"""
        val = self._emu.read_byte(0x904)
        labels = {
        0: "off",
        1: "on"
        }
        return labels.get(val, "unknown")

    @property
    def src_time_remaining(self) -> int:
        """Level timer (ticks)"""
        return self._emu.read_byte(0x905)

    @property
    def src_puzzle_status(self) -> str:
        """Puzzle state: 0=unsolved, 1=solved, 2=complete"""
        val = self._emu.read_byte(0x906)
        labels = {
        0: "off",
        1: "on"
        }
        return labels.get(val, "unknown")

    @property
    def src_diamonds_coll(self) -> int:
        """Diamonds collected"""
        return self._emu.read_byte(0x907)

    @property
    def src_earth_coll(self) -> int:
        """Earth collected (for filling traps)"""
        return self._emu.read_byte(0x908)

    @property
    def src_player_x(self) -> int:
        """---- Player Position ----"""
        return self._emu.read_byte(0x910)

    @property
    def src_player_y(self) -> int:
        """PLAYER_Y constant"""
        return self._emu.read_byte(0x911)

    @property
    def src_player_dir(self) -> int:
        """0=up, 1=right, 2=down, 3=left"""
        return self._emu.read_byte(0x912)

    @property
    def src_level_ptr_lo(self) -> int:
        """---- Level Data Pointer ----"""
        return self._emu.read_byte(0x920)

    @property
    def src_level_ptr_hi(self) -> int:
        """LEVEL_PTR_HI constant"""
        return self._emu.read_byte(0x921)

    @property
    def src_enemy_start(self) -> int:
        """32 bytes: 8 bytes x 4 enemies"""
        return self._emu.read_byte(0x930)

    @property
    def src_diamond_data(self) -> int:
        """60 bytes: x,y pairs"""
        return self._emu.read_byte(0x980)

    @property
    def src_trap_data(self) -> int:
        """20 bytes: x,y pairs"""
        return self._emu.read_byte(0x9c0)

    @property
    def src_try_up(self) -> int:
        """tryUp data label"""
        return self._emu.read_byte(0x1197)

    @property
    def src_undo_up(self) -> int:
        """undoUp data label"""
        return self._emu.read_byte(0x119e)

    @property
    def src_try_right(self) -> int:
        """tryRight data label"""
        return self._emu.read_byte(0x11a0)

    @property
    def src_undo_right(self) -> int:
        """undoRight data label"""
        return self._emu.read_byte(0x11a7)

    @property
    def src_try_down(self) -> int:
        """tryDown data label"""
        return self._emu.read_byte(0x11a9)

    @property
    def src_undo_down(self) -> int:
        """undoDown data label"""
        return self._emu.read_byte(0x11b0)

    @property
    def src_try_left(self) -> int:
        """tryLeft data label"""
        return self._emu.read_byte(0x11b2)

    @property
    def src_undo_left(self) -> int:
        """undoLeft data label"""
        return self._emu.read_byte(0x11b9)

    @property
    def src_update_timer(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x11cb)

    @property
    def src_level_table(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x11d6)

    @property
    def src_screen_buf(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x11ee)

    @property
    def src_screen_buf(self) -> dict:
        """ScreenBuf data structure"""
        return {
        }

    @property
    def src_score_display(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x15ee)

    @property
    def src_high_score_table(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x15f4)


    def capture_all(self) -> dict:
        """Capture all known state in a single snapshot."""
        return {
            "src_score_lo": self.src_score_lo,
            "src_score_hi": self.src_score_hi,
            "src_lives": self.src_lives,
            "src_level_num": self.src_level_num,
            "src_reptol_state": self.src_reptol_state,
            "src_time_remaining": self.src_time_remaining,
            "src_puzzle_status": self.src_puzzle_status,
            "src_diamonds_coll": self.src_diamonds_coll,
            "src_earth_coll": self.src_earth_coll,
            "src_player_x": self.src_player_x,
            "src_player_y": self.src_player_y,
            "src_player_dir": self.src_player_dir,
            "src_level_ptr_lo": self.src_level_ptr_lo,
            "src_level_ptr_hi": self.src_level_ptr_hi,
            "src_enemy_start": self.src_enemy_start,
            "src_diamond_data": self.src_diamond_data,
            "src_trap_data": self.src_trap_data,
            "src_try_up": self.src_try_up,
            "src_undo_up": self.src_undo_up,
            "src_try_right": self.src_try_right,
            "src_undo_right": self.src_undo_right,
            "src_try_down": self.src_try_down,
            "src_undo_down": self.src_undo_down,
            "src_try_left": self.src_try_left,
            "src_undo_left": self.src_undo_left,
            "src_update_timer": self.src_update_timer,
            "src_level_table": self.src_level_table,
            "src_screen_buf": self.src_screen_buf,
            "src_screen_buf": self.src_screen_buf,
            "src_score_display": self.src_score_display,
            "src_high_score_table": self.src_high_score_table
        }

