"""vault-scanner — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215821

#!/usr/bin/env python3
"""
Vault Scanner — uDos Vault Indexing & Consolidation Tool

Uses the .compost system and feed spool to:
  1. Scan all Vault docs and build a content index
  2. Extract locked specs (latest versions)
  3. Identify duplicates and redundant content
  4. Archive old versions to .compost/ (elastic trash)
  5. Generate a consolidated index

Usage:
  python vault-scanner.py scan          # Full scan + index
  python vault-scanner.py index         # Just rebuild index
  python vault-scanner.py dedup         # Find duplicates
  python vault-scanner.py archive       # Archive old versions to .compost/
  python vault-scanner.py report        # Generate consolidation report
  python vault-scanner.py feed          # Write scan results to feed spool
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

# ─── Configuration ───────────────────────────────────────────────────────────


from vault-scanner_other import *  # other
from vault-scanner_vault import *  # vault

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215821_vault-scanner.py