// renderer — slim entry point (modules split by file-splitter)
// Auto-generated by file-splitter on 20260618_215622



export * from "./renderer_other";  // other
export * from "./renderer_dashboard";  // dashboard

// Original file backed up to:
//   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215622_renderer.js