// other module — extracted from renderer.js
// Auto-generated by file-splitter on 20260618_215622



export function renderBundle(bundle, overrides = {}) {
  const { lens, skin, layout, meta } = bundle;

  // Check for dark mode preference
  const prefersDark = overrides._darkMode !== undefined
    ? overrides._darkMode
    : (lens?.features?.dark_mode === true);

  // Merge runtime overrides into LENS
  const activeLens = applyOverrides(lens, overrides);

  // Resolve all template variables
  const resolvedLayout = resolveLayoutTemplates(layout, activeLens);

  // Generate CSS from SKIN (with dark mode support)
  const css = generateSkinCSS(skin, prefersDark);

  // Generate HTML from Layout
  const html = renderLayout(resolvedLayout, activeLens, skin);

  // Generate JS for runtime interactivity (with dark mode toggle)
  const js = generateRuntimeJS(bundle.id, activeLens, skin, prefersDark);

  return `<!DOCTYPE html>
<html lang="en" data-usx-bundle="${bundle.id}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${bundle.name || 'USX Surface'}</title>
  <style>
    /* USX Reset */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { width: 100%; height: 100%; overflow: hidden; }
    body { font-family: system-ui, -apple-system, sans-serif; }
    
    /* USX Theme Variables — Light Mode */
    :root {
      ${generateCSSVariables(skin, false)}
    }
    
    /* USX Theme Variables — Dark Mode */
    @media (prefers-color-scheme: dark) {
      :root {
        ${generateCSSVariables(skin, true)}
      }
    }
    
    /* USX Dark Mode Class (for manual toggle) */
    :root.usx-dark-mode {
      ${generateCSSVariables(skin, true)}
    }
    
    /* USX Component Styles */
    ${css}
    
    /* USX Layout Styles */
    ${generateLayoutCSS(layout)}
    
    /* USX Animation Keyframes */
    @keyframes usx-fade-in {
      from { opacity: 0; }
      to { opacity: 1; }
    }
    @keyframes usx-fade-out {
      from { opacity: 1; }
      to { opacity: 0; }
    }
    @keyframes usx-slide-in-up {
      from { transform: translateY(20px); opacity: 0; }
      to { transform: translateY(0); opacity: 1; }
    }
    @keyframes usx-slide-in-down {
      from { transform: translateY(-20px); opacity: 0; }
      to { transform: translateY(0); opacity: 1; }
    }
    @keyframes usx-slide-in-left {
      from { transform: translateX(-20px); opacity: 0; }
      to { transform: translateX(0); opacity: 1; }
    }
    @keyframes usx-slide-in-right {
      from { transform: translateX(20px); opacity: 0; }
      to { transform: translateX(0); opacity: 1; }
    }
    @keyframes usx-scale-in {
      from { transform: scale(0.9); opacity: 0; }
      to { transform: scale(1); opacity: 1; }
    }
    @keyframes usx-rotate-in {
      from { transform: rotate(-10deg); opacity: 0; }
      to { transform: rotate(0); opacity: 1; }
    }
    @keyframes usx-bounce-in {
      0% { transform: scale(0); opacity: 0; }
      50% { transform: scale(1.15); }
      70% { transform: scale(0.95); }
      100% { transform: scale(1); opacity: 1; }
    }
    @keyframes usx-pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.5; }
    }
    @keyframes usx-shake {
      0%, 100% { transform: translateX(0); }
      25% { transform: translateX(-5px); }
      75% { transform: translateX(5px); }
    }
    @keyframes usx-spin {
      from { transform: rotate(0deg); }
      to { transform: rotate(360deg); }
    }
    
    /* USX Animation Classes */
    .usx-animate-fade-in { animation: usx-fade-in 0.3s ease-out both; }
    .usx-animate-fade-out { animation: usx-fade-out 0.3s ease-in both; }
    .usx-animate-slide-in-up { animation: usx-slide-in-up 0.3s ease-out both; }
    .usx-animate-slide-in-down { animation: usx-slide-in-down 0.3s ease-out both; }
    .usx-animate-slide-in-left { animation: usx-slide-in-left 0.3s ease-out both; }
    .usx-animate-slide-in-right { animation: usx-slide-in-right 0.3s ease-out both; }
    .usx-animate-scale-in { animation: usx-scale-in 0.3s ease-out both; }
    .usx-animate-rotate-in { animation: usx-rotate-in 0.3s ease-out both; }
    .usx-animate-bounce-in { animation: usx-bounce-in 0.5s ease-out both; }
    .usx-animate-pulse { animation: usx-pulse 2s ease-in-out infinite; }
    .usx-animate-shake { animation: usx-shake 0.5s ease-in-out; }
    .usx-animate-spin { animation: usx-spin 1s linear infinite; }
    
    /* USX Staggered Animation Support */
    .usx-stagger > .usx-widget {
      opacity: 0;
      animation: usx-fade-in 0.3s ease-out forwards;
    }
    .usx-stagger > .usx-widget:nth-child(1) { animation-delay: 0ms; }
    .usx-stagger > .usx-widget:nth-child(2) { animation-delay: 50ms; }
    .usx-stagger > .usx-widget:nth-child(3) { animation-delay: 100ms; }
    .usx-stagger > .usx-widget:nth-child(4) { animation-delay: 150ms; }
    .usx-stagger > .usx-widget:nth-child(5) { animation-delay: 200ms; }
    .usx-stagger > .usx-widget:nth-child(6) { animation-delay: 250ms; }
    .usx-stagger > .usx-widget:nth-child(7) { animation-delay: 300ms; }
    .usx-stagger > .usx-widget:nth-child(8) { animation-delay: 350ms; }
    .usx-stagger > .usx-widget:nth-child(9) { animation-delay: 400ms; }
    .usx-stagger > .usx-widget:nth-child(10) { animation-delay: 450ms; }
    
    /* Dark Mode Toggle Button */
    .usx-dark-toggle {
      position: fixed; bottom: 16px; right: 16px;
      width: 40px; height: 40px; border-radius: 50%;
      border: 1px solid var(--usx-border, #ddd);
      background: var(--usx-surface, white);
      color: var(--usx-text, #333);
      cursor: pointer; font-size: 18px;
      display: flex; align-items: center; justify-content: center;
      box-shadow: 0 2px 8px rgba(0,0,0,0.15);
      z-index: 9999; transition: all 0.2s;
    }
    .usx-dark-toggle:hover { transform: scale(1.1); }
  </style>
</head>
<body>
  <div id="usx-root" class="usx-surface" data-usx-surface="${bundle.id}">
    ${html}
  </div>
  <button class="usx-dark-toggle" onclick="usx.toggleDarkMode()" title="Toggle dark mode" id="dark-toggle">${prefersDark ? '☀️' : '🌙'}</button>
  <script>
    // USX Runtime
    ${js}
  </script>
</body>
</html>`;
}

// ─── LENS Resolution ───────────────────────────────────────────────

/**
 * Apply runtime overrides to LENS variables.
 */

function applyOverrides(lens, overrides) {
  const merged = JSON.parse(JSON.stringify(lens));
  
  for (const [path, value] of Object.entries(overrides)) {
    const keys = path.split('.');
    let current = merged;
    for (let i = 0; i < keys.length - 1; i++) {
      if (!current[keys[i]]) current[keys[i]] = {};
      current = current[keys[i]];
    }
    current[keys[keys.length - 1]] = value;
  }
  
  return merged;
}

/**
 * Resolve {{template}} variables in layout content.
 */

function resolveLayoutTemplates(layout, lens) {
  const resolved = JSON.parse(JSON.stringify(layout));
  
  function resolveNode(node) {
    if (!node || typeof node !== 'object') return;
    
    // Resolve content strings
    if (node.content) {
      for (const [key, value] of Object.entries(node.content)) {
        if (typeof value === 'string' && value.includes('{{')) {
          node.content[key] = resolveTemplate(value, lens);
        }
      }
    }
    
    // Resolve condition expressions
    if (node.condition && typeof node.condition === 'string') {
      try {
        node._visible = evaluateCondition(node.condition, lens);
      } catch {
        node._visible = true;
      }
    }
    
    // Resolve children
    if (node.children) {
      node.children.forEach(resolveNode);
    }
  }
  
  if (resolved.root) resolveNode(resolved.root);
  if (resolved.widgets) resolved.widgets.forEach(resolveNode);
  
  return resolved;
}

/**
 * Evaluate a simple condition expression against LENS.
 */

function evaluateCondition(condition, lens) {
  // Support simple patterns: "variables.isLoggedIn", "!variables.isLoggedIn"
  const trimmed = condition.trim();
  const negate = trimmed.startsWith('!');
  const path = negate ? trimmed.slice(1).trim() : trimmed;
  const value = resolvePath(lens, path);
  return negate ? !value : !!value;
}

// ─── SKIN → CSS Generation ─────────────────────────────────────────

/**
 * Generate CSS variables from SKIN colors.
 * @param {Object} skin - SKIN definition
 * @param {boolean} [dark=false] - Use dark mode values
 */

function generateCSSVariables(skin, dark = false) {
  if (!skin || !skin.colors) return '';
  
  const vars = [];
  for (const [name, color] of Object.entries(skin.colors)) {
    const value = dark && color.dark ? color.dark : color.light;
    if (color.css_variable) {
      vars.push(`  ${color.css_variable}: ${value};`);
    } else {
      vars.push(`  --usx-${name}: ${value};`);
    }
  }
  return vars.join('\n');
}

/**
 * Generate full CSS from SKIN definition.
 * @param {Object} skin - SKIN definition
 * @param {boolean} [dark=false] - Whether dark mode is active
 */

function generateSkinCSS(skin, dark = false) {
  if (!skin) return '';
  
  const parts = [];
  
  // Typography
  if (skin.typography) {
    for (const [name, type] of Object.entries(skin.typography)) {
      parts.push(`.usx-${name} {
  font-family: ${type.font_family};
  font-size: ${type.font_size};
  font-weight: ${type.font_weight || 400};
  line-height: ${type.line_height || 1.5};
  ${type.letter_spacing ? `letter-spacing: ${type.letter_spacing};` : ''}
  ${type.text_transform ? `text-transform: ${type.text_transform};` : ''}
}`);
    }
  }
  
  // Component skins
  if (skin.components) {
    for (const [name, component] of Object.entries(skin.components)) {
      if (component.base) {
        parts.push(`.usx-${name} { ${component.base} }`);
      }
      if (component.variants) {
        for (const [variant, styles] of Object.entries(component.variants)) {
          parts.push(`.usx-${name}.usx-${variant} { ${styles} }`);
        }
      }
      if (component.states) {
        for (const [state, styles] of Object.entries(component.states)) {
          parts.push(`.usx-${name}.usx-state-${state} { ${styles} }`);
        }
      }
    }
  }
  
  // Effects
  if (skin.effects) {
    for (const [name, effect] of Object.entries(skin.effects)) {
      if (effect.css) {
        parts.push(`.usx-effect-${name} { ${effect.css} }`);
      }
    }
  }
  
  return parts.join('\n\n');
}

/**
 * Generate layout-specific CSS.
 */

function generateLayoutCSS(layout) {
  if (!layout) return '';
  
  const parts = [];
  
  // Viewport
  if (layout.viewport) {
    parts.push(`#usx-root {
  width: ${layout.viewport.width || '100%'};
  height: ${layout.viewport.height || '100%'};
  ${layout.viewport.max_width ? `max-width: ${layout.viewport.max_width};` : ''}
  ${layout.viewport.min_width ? `min-width: ${layout.viewport.min_width};` : ''}
  overflow: auto;
}`);
  }
  
  // Grid
  if (layout.grid) {
    parts.push(`.usx-grid {
  display: grid;
  ${layout.grid.template_columns ? `grid-template-columns: ${layout.grid.template_columns};` : ''}
  ${layout.grid.template_rows ? `grid-template-rows: ${layout.grid.template_rows};` : ''}
  ${layout.grid.gap ? `gap: ${layout.grid.gap};` : ''}
}`);
  }
  
  return parts.join('\n\n');
}

// ─── Layout → HTML Generation ──────────────────────────────────────

/**
 * Render a layout to HTML.
 */

function renderLayout(layout, lens, skin) {
  if (!layout) return '<div class="usx-empty">No layout defined</div>';
  
  if (layout.root) {
    return renderWidget(layout.root, lens, skin);
  }
  
  if (layout.widgets) {
    return layout.widgets
      .map(w => renderWidget(w, lens, skin))
      .join('\n');
  }
  
  return '<div class="usx-empty">Empty layout</div>';
}

/**
 * Render a single widget to HTML.
 */
function renderWidget(widget, lens, skin) {
  if (!widget) return '';
  
  // Check visibility condition
  if (widget._visible === false) return '';
  if (widget.condition && widget._visible === false) return '';
  
  const classes = ['usx-widget', `usx-widget-${widget.type}`];
  const styles = [];
  const attrs = [`data-widget-id="${widget.id}"`, `data-widget-type="${widget.type}"`];
  
  // Apply animation
  if (widget.animation) {
    const anim = widget.animation;
    if (typeof anim === 'string') {
      classes.push(`usx-animate-${anim}`);
    } else if (anim.enter) {
      classes.push(`usx-animate-${anim.enter}`);
    }
    if (anim?.stagger) {
      classes.push('usx-stagger');
    }
    if (anim?.duration) {
      styles.push(`animation-duration: ${anim.duration}ms`);
    }
    if (anim?.delay) {
      styles.push(`animation-delay: ${anim.delay}ms`);
    }
  }
  
  // Apply skin reference
  if (widget.skin_ref) {
    const skinPath = widget.skin_ref;
    if (skin && resolvePath(skin, skinPath)) {
      classes.push(`usx-${skinPath.split('.').pop()}`);
    } else {
      classes.push(`usx-${skinPath.replace(/\./g, '-')}`);
    }
  }
  
  // Apply bounds
  if (widget.bounds) {
    styles.push(
      `position: absolute`,
      `left: ${widget.bounds.x}${widget.bounds.unit || 'px'}`,
      `top: ${widget.bounds.y}${widget.bounds.unit || 'px'}`,
      `width: ${widget.bounds.width}${widget.bounds.unit || 'px'}`,
      `height: ${widget.bounds.height}${widget.bounds.unit || 'px'}`
    );
  }
  
  // Apply props as inline styles
  if (widget.props) {
    if (widget.props.opacity) styles.push(`opacity: ${widget.props.opacity}`);
    if (widget.props.borderRadius) styles.push(`border-radius: ${widget.props.borderRadius}px`);
    if (widget.props.visible === false) styles.push(`display: none`);
  }
  
  // Build style string
  const styleStr = styles.length > 0 ? ` style="${styles.join('; ')}"` : '';
  const classStr = classes.length > 0 ? ` class="${classes.join(' ')}"` : '';
  const attrStr = attrs.join(' ');
  
  // Render children
  let childrenHtml = '';
  if (widget.children) {
    childrenHtml = widget.children
      .map(c => renderWidget(c, lens, skin))
      .join('\n');
  }
  
  // Handle repeat
  if (widget.repeat && lens) {
    const source = resolvePath(lens, widget.repeat.source);
    if (Array.isArray(source)) {
      childrenHtml = source.map((item, index) => {
        const context = { [widget.repeat.as]: item, index };
        return widget.children
          ? widget.children.map(c => renderWidgetWithContext(c, lens, skin, context)).join('\n')
          : '';
      }).join('\n');
    }
  }
  
  // Render based on widget type
  switch (widget.type) {
    case 'container':
      return `<div${classStr}${styleStr}${attrStr}>\n${childrenHtml}\n</div>`;
    
    case 'text':
      return `<span${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.text || '')}</span>`;
    
    case 'heading': {
      const level = widget.props?.level || 1;
      return `<h${level}${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.text || '')}</h${level}>`;
    }
    
    case 'button': {
      const events = widget.events ? ` onclick="usx.handleEvent('${widget.id}', 'onClick', event)"` : '';
      return `<button${classStr}${styleStr}${attrStr}${events}>${escapeHtml(widget.content?.label || widget.content?.text || 'Button')}</button>`;
    }
    
    case 'input':
      return `<input${classStr}${styleStr}${attrStr} type="${widget.props?.inputType || 'text'}" placeholder="${escapeHtml(widget.content?.placeholder || '')}" value="${escapeHtml(widget.content?.value || '')}" />`;
    
    case 'image':
      return `<img${classStr}${styleStr}${attrStr} src="${escapeHtml(widget.content?.src || '')}" alt="${escapeHtml(widget.content?.alt || '')}" />`;
    
    case 'icon':
      return `<span${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.icon || '•')}</span>`;
    
    case 'divider':
      return `<hr${classStr}${styleStr}${attrStr} />`;
    
    case 'card':
      return `<div${classStr}${styleStr}${attrStr}>\n${childrenHtml}\n</div>`;
    
    case 'code_block':
      return `<pre${classStr}${styleStr}${attrStr}><code>${escapeHtml(widget.content?.code || widget.content?.text || '')}</code></pre>`;
    
    case 'quote':
      return `<blockquote${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.text || '')}</blockquote>`;
    
    case 'callout':
      return `<div${classStr}${styleStr}${attrStr} role="alert">${escapeHtml(widget.content?.text || '')}</div>`;
    
    case 'list': {
      const items = widget.content?.items || [];
      const tag = widget.props?.ordered ? 'ol' : 'ul';
      return `<${tag}${classStr}${styleStr}${attrStr}>${items.map(item => `<li>${escapeHtml(item)}</li>`).join('\n')}</${tag}>`;
    }
    
    case 'table': {
      const headers = widget.content?.headers || [];
      const rows = widget.content?.rows || [];
      return `<table${classStr}${styleStr}${attrStr}>
  <thead><tr>${headers.map(h => `<th>${escapeHtml(h)}</th>`).join('')}</tr></thead>
  <tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join('\n')}</tbody>
</table>`;
    }
    
    case 'todo':
      return `<label${classStr}${styleStr}${attrStr}><input type="checkbox" ${widget.content?.checked ? 'checked' : ''} /> ${escapeHtml(widget.content?.text || '')}</label>`;
    
    case 'toggle':
      return `<label${classStr}${styleStr}${attrStr} class="usx-toggle"><input type="checkbox" role="switch" ${widget.content?.active ? 'checked' : ''} /> ${escapeHtml(widget.content?.label || '')}</label>`;
    
    case 'iframe':
      return `<iframe${classStr}${styleStr}${attrStr} src="${escapeHtml(widget.content?.src || '')}" ${widget.props?.allowFullscreen ? 'allowfullscreen' : ''}></iframe>`;
    
    case 'custom':
      return `<div${classStr}${styleStr}${attrStr} data-custom-type="${widget.props?.customType || ''}">${childrenHtml || escapeHtml(widget.content?.text || '')}</div>`;
    
    default:
      return `<div${classStr}${styleStr}${attrStr}>${childrenHtml || escapeHtml(widget.content?.text || '')}</div>`;
  }
}

/**
 * Render a widget with additional template context (for repeat loops).
 */
function renderWidgetWithContext(widget, lens, skin, context) {
  const widgetStr = JSON.stringify(widget);
  const resolvedStr = widgetStr.replace(/\{\{([^}]+)\}\}/g, (match, path) => {
    const trimmed = path.trim();
    if (context[trimmed] !== undefined) {
      return String(context[trimmed]);
    }
    const value = resolvePath(lens, trimmed);
    return value !== undefined ? String(value) : match;
  });
  
  const resolvedWidget = JSON.parse(resolvedStr);
  return renderWidget(resolvedWidget, lens, skin);
}

// ─── Runtime JavaScript ────────────────────────────────────────────

/**
 * Generate runtime JavaScript for the bundle.
 * @param {string} bundleId - Bundle ID
 * @param {Object} lens - LENS state
 * @param {Object} [skin] - SKIN definition (for dark mode)
 * @param {boolean} [prefersDark=false] - Initial dark mode state
 */

function generateRuntimeJS(bundleId, lens, skin, prefersDark = false) {
  return `
(function() {
  'use strict';
  
  const USX = {
    bundleId: '${bundleId}',
    lens: ${JSON.stringify(lens)},
    darkMode: ${prefersDark},
    
    // Event handler
    handleEvent(widgetId, eventType, event) {
      const widget = document.querySelector(\`[data-widget-id="\${widgetId}"]\`);
      if (!widget) return;
      
      // Dispatch custom event for external listeners
      const detail = { widgetId, eventType, event, lens: this.lens };
      document.dispatchEvent(new CustomEvent('usx:event', { detail }));
      
      // Log for debugging
      if (window.__USX_DEBUG) {
        console.log('[USX Event]', widgetId, eventType, event);
      }
    },
    
    // Update a LENS variable and re-render
    setVariable(path, value) {
      const keys = path.split('.');
      let current = this.lens;
      for (let i = 0; i < keys.length - 1; i++) {
        if (!current[keys[i]]) current[keys[i]] = {};
        current = current[keys[i]];
      }
      current[keys[keys.length - 1]] = value;
      
      // Dispatch update event
      document.dispatchEvent(new CustomEvent('usx:update', {
        detail: { path, value, lens: this.lens }
      }));
    },
    
    // Get a LENS variable
    getVariable(path) {
      return path.split('.').reduce((obj, key) => 
        obj && obj[key] !== undefined ? obj[key] : undefined, this.lens);
    },
    
    // Toggle dark mode
    toggleDarkMode() {
      this.darkMode = !this.darkMode;
      const root = document.documentElement;
      const toggle = document.getElementById('dark-toggle');
      
      if (this.darkMode) {
        root.classList.add('usx-dark-mode');
        if (toggle) toggle.textContent = '☀️';
      } else {
        root.classList.remove('usx-dark-mode');
        if (toggle) toggle.textContent = '🌙';
      }
      
      // Dispatch dark mode event
      document.dispatchEvent(new CustomEvent('usx:darkmode', {
        detail: { darkMode: this.darkMode }
      }));
    },
    
    // Check if dark mode is active
    isDarkMode() {
      return this.darkMode || document.documentElement.classList.contains('usx-dark-mode');
    }
  };
  
  // Expose globally
  window.usx = USX;
  
  // Apply initial dark mode if set
  if (${prefersDark}) {
    document.documentElement.classList.add('usx-dark-mode');
  }
  
  // Debug mode
  if (window.location.hash === '#debug') {
    window.__USX_DEBUG = true;
    console.log('[USX] Bundle:', '${bundleId}');
    console.log('[USX] LENS:', USX.lens);
    console.log('[USX] Dark Mode:', USX.darkMode);
  }
})();
`;
}

// ─── Utilities ─────────────────────────────────────────────────────

/**
 * Escape HTML special characters.
 */

function escapeHtml(str) {
  if (typeof str !== 'string') return String(str || '');
  return str
    .replace(/&/g, '&')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"')
    .replace(/'/g, '&#039;');
}

export {
  renderBundle,
  renderWidget,
  generateSkinCSS,
  generateCSSVariables,
  generateRuntimeJS,
  escapeHtml
};

export default { renderBundle };

