// dashboard module — extracted from renderer.js
// Auto-generated by file-splitter on 20260618_215622



function renderWidget(widget, lens, skin) {
  if (!widget) return '';
  
  // Check visibility condition
  if (widget._visible === false) return '';
  if (widget.condition && widget._visible === false) return '';
  
  const classes = ['usx-widget', `usx-widget-${widget.type}`];
  const styles = [];
  const attrs = [`data-widget-id="${widget.id}"`, `data-widget-type="${widget.type}"`];
  
  // Apply animation
  if (widget.animation) {
    const anim = widget.animation;
    if (typeof anim === 'string') {
      classes.push(`usx-animate-${anim}`);
    } else if (anim.enter) {
      classes.push(`usx-animate-${anim.enter}`);
    }
    if (anim?.stagger) {
      classes.push('usx-stagger');
    }
    if (anim?.duration) {
      styles.push(`animation-duration: ${anim.duration}ms`);
    }
    if (anim?.delay) {
      styles.push(`animation-delay: ${anim.delay}ms`);
    }
  }
  
  // Apply skin reference
  if (widget.skin_ref) {
    const skinPath = widget.skin_ref;
    if (skin && resolvePath(skin, skinPath)) {
      classes.push(`usx-${skinPath.split('.').pop()}`);
    } else {
      classes.push(`usx-${skinPath.replace(/\./g, '-')}`);
    }
  }
  
  // Apply bounds
  if (widget.bounds) {
    styles.push(
      `position: absolute`,
      `left: ${widget.bounds.x}${widget.bounds.unit || 'px'}`,
      `top: ${widget.bounds.y}${widget.bounds.unit || 'px'}`,
      `width: ${widget.bounds.width}${widget.bounds.unit || 'px'}`,
      `height: ${widget.bounds.height}${widget.bounds.unit || 'px'}`
    );
  }
  
  // Apply props as inline styles
  if (widget.props) {
    if (widget.props.opacity) styles.push(`opacity: ${widget.props.opacity}`);
    if (widget.props.borderRadius) styles.push(`border-radius: ${widget.props.borderRadius}px`);
    if (widget.props.visible === false) styles.push(`display: none`);
  }
  
  // Build style string
  const styleStr = styles.length > 0 ? ` style="${styles.join('; ')}"` : '';
  const classStr = classes.length > 0 ? ` class="${classes.join(' ')}"` : '';
  const attrStr = attrs.join(' ');
  
  // Render children
  let childrenHtml = '';
  if (widget.children) {
    childrenHtml = widget.children
      .map(c => renderWidget(c, lens, skin))
      .join('\n');
  }
  
  // Handle repeat
  if (widget.repeat && lens) {
    const source = resolvePath(lens, widget.repeat.source);
    if (Array.isArray(source)) {
      childrenHtml = source.map((item, index) => {
        const context = { [widget.repeat.as]: item, index };
        return widget.children
          ? widget.children.map(c => renderWidgetWithContext(c, lens, skin, context)).join('\n')
          : '';
      }).join('\n');
    }
  }
  
  // Render based on widget type
  switch (widget.type) {
    case 'container':
      return `<div${classStr}${styleStr}${attrStr}>\n${childrenHtml}\n</div>`;
    
    case 'text':
      return `<span${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.text || '')}</span>`;
    
    case 'heading': {
      const level = widget.props?.level || 1;
      return `<h${level}${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.text || '')}</h${level}>`;
    }
    
    case 'button': {
      const events = widget.events ? ` onclick="usx.handleEvent('${widget.id}', 'onClick', event)"` : '';
      return `<button${classStr}${styleStr}${attrStr}${events}>${escapeHtml(widget.content?.label || widget.content?.text || 'Button')}</button>`;
    }
    
    case 'input':
      return `<input${classStr}${styleStr}${attrStr} type="${widget.props?.inputType || 'text'}" placeholder="${escapeHtml(widget.content?.placeholder || '')}" value="${escapeHtml(widget.content?.value || '')}" />`;
    
    case 'image':
      return `<img${classStr}${styleStr}${attrStr} src="${escapeHtml(widget.content?.src || '')}" alt="${escapeHtml(widget.content?.alt || '')}" />`;
    
    case 'icon':
      return `<span${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.icon || '•')}</span>`;
    
    case 'divider':
      return `<hr${classStr}${styleStr}${attrStr} />`;
    
    case 'card':
      return `<div${classStr}${styleStr}${attrStr}>\n${childrenHtml}\n</div>`;
    
    case 'code_block':
      return `<pre${classStr}${styleStr}${attrStr}><code>${escapeHtml(widget.content?.code || widget.content?.text || '')}</code></pre>`;
    
    case 'quote':
      return `<blockquote${classStr}${styleStr}${attrStr}>${escapeHtml(widget.content?.text || '')}</blockquote>`;
    
    case 'callout':
      return `<div${classStr}${styleStr}${attrStr} role="alert">${escapeHtml(widget.content?.text || '')}</div>`;
    
    case 'list': {
      const items = widget.content?.items || [];
      const tag = widget.props?.ordered ? 'ol' : 'ul';
      return `<${tag}${classStr}${styleStr}${attrStr}>${items.map(item => `<li>${escapeHtml(item)}</li>`).join('\n')}</${tag}>`;
    }
    
    case 'table': {
      const headers = widget.content?.headers || [];
      const rows = widget.content?.rows || [];
      return `<table${classStr}${styleStr}${attrStr}>
  <thead><tr>${headers.map(h => `<th>${escapeHtml(h)}</th>`).join('')}</tr></thead>
  <tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join('\n')}</tbody>
</table>`;
    }
    
    case 'todo':
      return `<label${classStr}${styleStr}${attrStr}><input type="checkbox" ${widget.content?.checked ? 'checked' : ''} /> ${escapeHtml(widget.content?.text || '')}</label>`;
    
    case 'toggle':
      return `<label${classStr}${styleStr}${attrStr} class="usx-toggle"><input type="checkbox" role="switch" ${widget.content?.active ? 'checked' : ''} /> ${escapeHtml(widget.content?.label || '')}</label>`;
    
    case 'iframe':
      return `<iframe${classStr}${styleStr}${attrStr} src="${escapeHtml(widget.content?.src || '')}" ${widget.props?.allowFullscreen ? 'allowfullscreen' : ''}></iframe>`;
    
    case 'custom':
      return `<div${classStr}${styleStr}${attrStr} data-custom-type="${widget.props?.customType || ''}">${childrenHtml || escapeHtml(widget.content?.text || '')}</div>`;
    
    default:
      return `<div${classStr}${styleStr}${attrStr}>${childrenHtml || escapeHtml(widget.content?.text || '')}</div>`;
  }
}

/**
 * Render a widget with additional template context (for repeat loops).
 */

function renderWidgetWithContext(widget, lens, skin, context) {
  const widgetStr = JSON.stringify(widget);
  const resolvedStr = widgetStr.replace(/\{\{([^}]+)\}\}/g, (match, path) => {
    const trimmed = path.trim();
    if (context[trimmed] !== undefined) {
      return String(context[trimmed]);
    }
    const value = resolvePath(lens, trimmed);
    return value !== undefined ? String(value) : match;
  });
  
  const resolvedWidget = JSON.parse(resolvedStr);
  return renderWidget(resolvedWidget, lens, skin);
}

// ─── Runtime JavaScript ────────────────────────────────────────────

/**
 * Generate runtime JavaScript for the bundle.
 * @param {string} bundleId - Bundle ID
 * @param {Object} lens - LENS state
 * @param {Object} [skin] - SKIN definition (for dark mode)
 * @param {boolean} [prefersDark=false] - Initial dark mode state
 */
function generateRuntimeJS(bundleId, lens, skin, prefersDark = false) {
  return `
(function() {
  'use strict';
  
  const USX = {
    bundleId: '${bundleId}',
    lens: ${JSON.stringify(lens)},
    darkMode: ${prefersDark},
    
    // Event handler
    handleEvent(widgetId, eventType, event) {
      const widget = document.querySelector(\`[data-widget-id="\${widgetId}"]\`);
      if (!widget) return;
      
      // Dispatch custom event for external listeners
      const detail = { widgetId, eventType, event, lens: this.lens };
      document.dispatchEvent(new CustomEvent('usx:event', { detail }));
      
      // Log for debugging
      if (window.__USX_DEBUG) {
        console.log('[USX Event]', widgetId, eventType, event);
      }
    },
    
    // Update a LENS variable and re-render
    setVariable(path, value) {
      const keys = path.split('.');
      let current = this.lens;
      for (let i = 0; i < keys.length - 1; i++) {
        if (!current[keys[i]]) current[keys[i]] = {};
        current = current[keys[i]];
      }
      current[keys[keys.length - 1]] = value;
      
      // Dispatch update event
      document.dispatchEvent(new CustomEvent('usx:update', {
        detail: { path, value, lens: this.lens }
      }));
    },
    
    // Get a LENS variable
    getVariable(path) {
      return path.split('.').reduce((obj, key) => 
        obj && obj[key] !== undefined ? obj[key] : undefined, this.lens);
    },
    
    // Toggle dark mode
    toggleDarkMode() {
      this.darkMode = !this.darkMode;
      const root = document.documentElement;
      const toggle = document.getElementById('dark-toggle');
      
      if (this.darkMode) {
        root.classList.add('usx-dark-mode');
        if (toggle) toggle.textContent = '☀️';
      } else {
        root.classList.remove('usx-dark-mode');
        if (toggle) toggle.textContent = '🌙';
      }
      
      // Dispatch dark mode event
      document.dispatchEvent(new CustomEvent('usx:darkmode', {
        detail: { darkMode: this.darkMode }
      }));
    },
    
    // Check if dark mode is active
    isDarkMode() {
      return this.darkMode || document.documentElement.classList.contains('usx-dark-mode');
    }
  };
  
  // Expose globally
  window.usx = USX;
  
  // Apply initial dark mode if set
  if (${prefersDark}) {
    document.documentElement.classList.add('usx-dark-mode');
  }
  
  // Debug mode
  if (window.location.hash === '#debug') {
    window.__USX_DEBUG = true;
    console.log('[USX] Bundle:', '${bundleId}');
    console.log('[USX] LENS:', USX.lens);
    console.log('[USX] Dark Mode:', USX.darkMode);
  }
})();
`;
}

// ─── Utilities ─────────────────────────────────────────────────────

/**
 * Escape HTML special characters.
 */
function escapeHtml(str) {
  if (typeof str !== 'string') return String(str || '');
  return str
    .replace(/&/g, '&')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"')
    .replace(/'/g, '&#039;');
}

export {
  renderBundle,
  renderWidget,
  generateSkinCSS,
  generateCSSVariables,
  generateRuntimeJS,
  escapeHtml
};

export default { renderBundle };

