// other module — extracted from index.js
// Auto-generated by file-splitter on 20260618_220150




export class Registry {
  constructor(dbPath = './usx-registry.db') {
    this.dbPath = resolve(dbPath);
    this.db = null;
    this.ready = false;
  }

  /**
   * Initialize the registry database.
   * Creates tables if they don't exist.
   */
  async init() {
    const Database = await import('better-sqlite3');
    
    // Ensure directory exists
    const dir = dirname(this.dbPath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    
    this.db = new Database.default(this.dbPath);
    this.db.pragma('journal_mode = WAL');
    this.db.pragma('foreign_keys = ON');
    
    this._createTables();
    this.ready = true;
    console.log(`📦 Registry initialized: ${this.dbPath}`);
    return this;
  }

  /**
   * Create database tables.
   */
  _createTables() {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS bundles (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        version TEXT NOT NULL DEFAULT '1.0.0',
        description TEXT DEFAULT '',
        source_tool TEXT DEFAULT 'manual',
        source_version TEXT DEFAULT '',
        exported_at TEXT DEFAULT '',
        exported_by TEXT DEFAULT '',
        file_path TEXT DEFAULT '',
        file_size INTEGER DEFAULT 0,
        imported_at TEXT DEFAULT (datetime('now')),
        updated_at TEXT DEFAULT (datetime('now')),
        lens_variables_count INTEGER DEFAULT 0,
        skin_colors_count INTEGER DEFAULT 0,
        layout_widgets_count INTEGER DEFAULT 0,
        raw_json TEXT
      );

      CREATE TABLE IF NOT EXISTS tags (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        bundle_id TEXT NOT NULL,
        tag TEXT NOT NULL,
        FOREIGN KEY (bundle_id) REFERENCES bundles(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS categories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        bundle_id TEXT NOT NULL,
        category TEXT NOT NULL,
        FOREIGN KEY (bundle_id) REFERENCES bundles(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS dependencies (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        bundle_id TEXT NOT NULL,
        depends_on TEXT NOT NULL,
        version_constraint TEXT DEFAULT '*',
        FOREIGN KEY (bundle_id) REFERENCES bundles(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS versions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        bundle_id TEXT NOT NULL,
        version TEXT NOT NULL,
        file_path TEXT DEFAULT '',
        imported_at TEXT DEFAULT (datetime('now')),
        raw_json TEXT,
        FOREIGN KEY (bundle_id) REFERENCES bundles(id) ON DELETE CASCADE
      );

      CREATE INDEX IF NOT EXISTS idx_tags_bundle ON tags(bundle_id);
      CREATE INDEX IF NOT EXISTS idx_tags_tag ON tags(tag);
      CREATE INDEX IF NOT EXISTS idx_categories_bundle ON categories(bundle_id);
      CREATE INDEX IF NOT EXISTS idx_bundles_name ON bundles(name);
      CREATE INDEX IF NOT EXISTS idx_bundles_source ON bundles(source_tool);
    `);

    // Enable FTS5 for full-text search
    try {
      this.db.exec(`
        CREATE VIRTUAL TABLE IF NOT EXISTS bundles_fts USING fts5(
          id UNINDEXED,
          name,
          description,
          tags,
          content='bundles',
          content_rowid='rowid'
        );
      `);
    } catch (err) {
      // FTS5 may not be available; search will fall back to LIKE
      console.warn('⚠️  FTS5 not available, falling back to LIKE search');
    }
  }

  // ─── Import ──────────────────────────────────────────────────────

  /**
   * Import a USX bundle from a file path.
   * @param {string} filePath - Path to .usx file
   * @returns {Object} Imported bundle metadata
   */
  importBundle(filePath) {
    if (!this.ready) throw new Error('Registry not initialized. Call init() first.');
    
    const resolvedPath = resolve(filePath);
    if (!existsSync(resolvedPath)) {
      throw new Error(`Bundle not found: ${resolvedPath}`);
    }
    
    const content = readFileSync(resolvedPath, 'utf-8');
    const bundle = JSON.parse(content);
    
    return this._storeBundle(bundle, resolvedPath);
  }

  /**
   * Import a bundle from a parsed JSON object.
   * @param {Object} bundle - USX bundle object
   * @param {string} [filePath] - Optional source file path
   * @returns {Object} Imported bundle metadata
   */
  importBundleFromObject(bundle, filePath = '') {
    if (!this.ready) throw new Error('Registry not initialized. Call init() first.');
    return this._storeBundle(bundle, filePath);
  }

  /**
   * Import all .usx files from a directory.
   * @param {string} dirPath - Directory to scan
   * @returns {Array} List of imported bundle metadata
   */
  importDirectory(dirPath) {
    const resolvedPath = resolve(dirPath);
    if (!existsSync(resolvedPath)) {
      throw new Error(`Directory not found: ${resolvedPath}`);
    }
    
    const files = readdirSync(resolvedPath)
      .filter(f => f.endsWith('.usx') || f.endsWith('.usx.json'))
      .map(f => resolve(resolvedPath, f));
    
    const results = [];
    for (const file of files) {
      try {
        results.push(this.importBundle(file));
      } catch (err) {
        console.error(`❌ Failed to import ${file}: ${err.message}`);
      }
    }
    
    return results;
  }

  /**
   * Store a bundle in the database.
   */
  _storeBundle(bundle, filePath) {
    const { id, name, version, description, source, lens, skin, layout, meta } = bundle;
    
    const lensVarCount = lens?.variables ? Object.keys(lens.variables).length : 0;
    const skinColorCount = skin?.colors ? Object.keys(skin.colors).length : 0;
    const widgetCount = layout?.root ? this._countWidgets(layout.root) : 0;
    
    const fileSize = filePath && existsSync(filePath)
      ? readFileSync(filePath).length
      : 0;
    
    const rawJson = JSON.stringify(bundle);
    
    const insertBundle = this.db.prepare(`
      INSERT OR REPLACE INTO bundles (
        id, name, version, description,
        source_tool, source_version, exported_at, exported_by,
        file_path, file_size, imported_at, updated_at,
        lens_variables_count, skin_colors_count, layout_widgets_count,
        raw_json
      ) VALUES (
        @id, @name, @version, @description,
        @source_tool, @source_version, @exported_at, @exported_by,
        @file_path, @file_size, datetime('now'), datetime('now'),
        @lens_vars, @skin_colors, @widgets,
        @raw_json
      )
    `);
    
    const insertTag = this.db.prepare(`
      INSERT OR IGNORE INTO tags (bundle_id, tag) VALUES (@bundle_id, @tag)
    `);
    
    const insertCategory = this.db.prepare(`
      INSERT OR IGNORE INTO categories (bundle_id, category) VALUES (@bundle_id, @category)
    `);
    
    const insertVersion = this.db.prepare(`
      INSERT INTO versions (bundle_id, version, file_path, raw_json)
      VALUES (@bundle_id, @version, @file_path, @raw_json)
    `);
    
    const transaction = this.db.transaction(() => {
      // Insert/update bundle
      insertBundle.run({
        id,
        name: name || id,
        version: version || '1.0.0',
        description: description || '',
        source_tool: source?.tool || 'manual',
        source_version: source?.version || '',
        exported_at: source?.exported_at || '',
        exported_by: source?.exported_by || '',
        file_path: filePath || '',
        file_size: fileSize,
        lens_vars: lensVarCount,
        skin_colors: skinColorCount,
        widgets: widgetCount,
        raw_json: rawJson
      });
      
      // Clear old tags/categories
      this.db.prepare('DELETE FROM tags WHERE bundle_id = ?').run(id);
      this.db.prepare('DELETE FROM categories WHERE bundle_id = ?').run(id);
      
      // Insert tags
      if (meta?.tags) {
        for (const tag of meta.tags) {
          insertTag.run({ bundle_id: id, tag });
        }
      }
      
      // Insert categories
      if (meta?.categories) {
        for (const category of meta.categories) {
          insertCategory.run({ bundle_id: id, category });
        }
      }
      
      // Insert version history
      insertVersion.run({
        bundle_id: id,
        version: version || '1.0.0',
        file_path: filePath || '',
        raw_json: rawJson
      });
      
      // Update FTS index
      this._updateFTS(id, name, description, meta?.tags);
    });
    
    transaction();
    
    return {
      id,
      name: name || id,
      version: version || '1.0.0',
      action: 'imported',
      lens_variables: lensVarCount,
      skin_colors: skinColorCount,
      widgets: widgetCount,
      tags: meta?.tags || [],
      categories: meta?.categories || []
    };
  }

  /**
   * Update the FTS index for a bundle.
   */
  _updateFTS(id, name, description, tags) {
    try {
      const tagsStr = Array.isArray(tags) ? tags.join(' ') : '';
      this.db.prepare(`
        INSERT INTO bundles_fts (rowid, id, name, description, tags)
        VALUES (
          (SELECT rowid FROM bundles WHERE id = ?),
          ?, ?, ?, ?
        )
      `).run(id, id, name || '', description || '', tagsStr);
    } catch {
      // FTS not available, skip
    }
  }

  // ─── Query ───────────────────────────────────────────────────────

  /**
   * Search bundles by query string.
   * @param {string} query - Search query
   * @param {Object} [options] - Search options
   * @param {number} [options.limit=20] - Max results
   * @param {number} [options.offset=0] - Result offset
   * @param {string} [options.tag] - Filter by tag
   * @param {string} [options.category] - Filter by category
   * @param {string} [options.source] - Filter by source tool
   * @returns {Array} Search results
   */
  search(query, options = {}) {
    if (!this.ready) throw new Error('Registry not initialized.');
    
    const { limit = 20, offset = 0, tag, category, source } = options;
    
    let sql = 'SELECT DISTINCT b.* FROM bundles b';
    const params = [];
    const conditions = [];
    
    // Full-text search
    if (query && query.trim()) {
      // Try FTS first, fall back to LIKE
      try {
        sql = `
          SELECT b.* FROM bundles_fts f
          JOIN bundles b ON b.id = f.id
          WHERE bundles_fts MATCH ?
        `;
        params.push(query);
      } catch {
        sql = 'SELECT DISTINCT b.* FROM bundles b';
        conditions.push('(b.name LIKE ? OR b.description LIKE ? OR b.id LIKE ?)');
        params.push(`%${query}%`, `%${query}%`, `%${query}%`);
      }
    }
    
    // Tag filter
    if (tag) {
      sql = `
        SELECT b.* FROM bundles b
        JOIN tags t ON t.bundle_id = b.id
      `;
      conditions.push('t.tag = ?');
      params.push(tag);
    }
    
    // Category filter
    if (category) {
      if (!sql.includes('JOIN categories')) {
        sql = `
          SELECT b.* FROM bundles b
          JOIN categories c ON c.bundle_id = b.id
        `;
      }
      conditions.push('c.category = ?');
      params.push(category);
    }
    
    // Source filter
    if (source) {
      conditions.push('b.source_tool = ?');
      params.push(source);
    }
    
    // Combine conditions
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    
    sql += ' ORDER BY b.updated_at DESC LIMIT ? OFFSET ?';
    params.push(limit, offset);
    
    const rows = this.db.prepare(sql).all(...params);
    
    return rows.map(row => ({
      id: row.id,
      name: row.name,
      version: row.version,
      description: row.description,
      source: row.source_tool,
      file_path: row.file_path,
      file_size: row.file_size,
      imported_at: row.imported_at,
      updated_at: row.updated_at,
      stats: {
        lens_variables: row.lens_variables_count,
        skin_colors: row.skin_colors_count,
        widgets: row.layout_widgets_count
      },
      tags: this.getTags(row.id),
      categories: this.getCategories(row.id)
    }));
  }

  /**
   * Get a bundle by ID.
   * @param {string} id - Bundle ID
   * @returns {Object|null} Bundle data or null
   */
  getBundle(id) {
    if (!this.ready) throw new Error('Registry not initialized.');
    
    const row = this.db.prepare('SELECT * FROM bundles WHERE id = ?').get(id);
    if (!row) return null;
    
    return {
      id: row.id,
      name: row.name,
      version: row.version,
      description: row.description,
      source: {
        tool: row.source_tool,
        version: row.source_version,
        exported_at: row.exported_at,
        exported_by: row.exported_by
      },
      file_path: row.file_path,
      file_size: row.file_size,
      imported_at: row.imported_at,
      updated_at: row.updated_at,
      stats: {
        lens_variables: row.lens_variables_count,
        skin_colors: row.skin_colors_count,
        widgets: row.layout_widgets_count
      },
      tags: this.getTags(id),
      categories: this.getCategories(id),
      raw_json: row.raw_json ? JSON.parse(row.raw_json) : null
    };
  }

  /**
   * List all bundles.
   * @param {Object} [options] - List options
   * @returns {Array} List of bundles
   */
  listBundles(options = {}) {
    return this.search('', options);
  }

  /**
   * Get tags for a bundle.
   */
  getTags(bundleId) {
    const rows = this.db.prepare('SELECT tag FROM tags WHERE bundle_id = ?').all(bundleId);
    return rows.map(r => r.tag);
  }

  /**
   * Get categories for a bundle.
   */
  getCategories(bundleId) {
    const rows = this.db.prepare('SELECT category FROM categories WHERE bundle_id = ?').all(bundleId);
    return rows.map(r => r.category);
  }

  /**
   * Get all unique tags across all bundles.
   * @returns {Array} List of {tag, count}
   */
  getAllTags() {
    return this.db.prepare(`
      SELECT tag, COUNT(*) as count FROM tags
      GROUP BY tag ORDER BY count DESC
    `).all();
  }

  /**
   * Get version history for a bundle.
   */
  getVersionHistory(bundleId) {
    return this.db.prepare(`
      SELECT version, file_path, imported_at
      FROM versions WHERE bundle_id = ?
      ORDER BY imported_at DESC
    `).all(bundleId);
  }

  /**
   * Delete a bundle from the registry.
   */
  deleteBundle(id) {
    if (!this.ready) throw new Error('Registry not initialized.');
    const result = this.db.prepare('DELETE FROM bundles WHERE id = ?').run(id);
    return result.changes > 0;
  }

  /**
   * Get registry statistics.
   * @returns {Object} Stats
   */
  getStats() {
    const total = this.db.prepare('SELECT COUNT(*) as count FROM bundles').get();
    const bySource = this.db.prepare(`
      SELECT source_tool, COUNT(*) as count FROM bundles
      GROUP BY source_tool ORDER BY count DESC
    `).all();
    const totalTags = this.db.prepare('SELECT COUNT(DISTINCT tag) as count FROM tags').get();
    const recentImports = this.db.prepare(`
      SELECT name, id, version, imported_at FROM bundles
      ORDER BY imported_at DESC LIMIT 5
    `).all();
    
    return {
      total_bundles: total.count,
      total_tags: totalTags.count,
      by_source: bySource,
      recent_imports: recentImports
    };
  }

  // ─── Utilities ───────────────────────────────────────────────────

  /**
   * Count widgets in a layout tree.
   */
  _countWidgets(node) {
    if (!node) return 0;
    let count = 1;
    if (node.children) {
      for (const child of node.children) {
        count += this._countWidgets(child);
      }
    }
    return count;
  }

  /**
   * Close the database connection.
   */
  close() {
    if (this.db) {
      this.db.close();
      this.ready = false;
    }
  }
}

// ─── Default Export ────────────────────────────────────────────────



export default Registry;

