// index — slim entry point (modules split by file-splitter)
// Auto-generated by file-splitter on 20260618_220150



export * from "./index_other";  // other
export { default } from "./index_other";  // re-export default (Registry)

// Original file backed up to:
//   /Users/fredbook/.snackbar/backups/file-splitter/20260618_220150_index.js