"""grid_parser — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215509

#!/usr/bin/env python3
"""
USXD ASCII Grid Parser - Python Implementation

This module provides functionality to parse ASCII grid formats into structured data
for USXD/OBF integration. It supports parsing ASCII grid text into structured formats
and converting structured data back to ASCII grid format.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Tuple, Union
import json
import re
from enum import Enum



from grid_parser_other import *  # other

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215509_grid_parser.py