"""processor — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215456

"""Emulation of the MOT-6502 Processor."""

import sys

from . import Memory



from processor_process import *  # process
from .processor_other import *  # other

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215456_processor.py