"""component_mapper — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215605

#!/usr/bin/env python3
"""
USXD Component Mapper - Python Implementation

This module provides functionality to map parsed grid components to ThinUI
renderable components, enabling the conversion from ASCII grids to interactive
UI elements.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Tuple, Union, Callable
import json
from enum import Enum
from ..usxd.grid_parser import GridCell, GridComponent, ParsedGrid, GridFormat, ASCIIGridParser



from component_mapper_other import *  # other
from component_mapper_map import *  # map

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215605_component_mapper.py