// validate-schema — slim entry point (modules split by file-splitter)
// Auto-generated by file-splitter on 20260618_220203



export * from "./validate-schema_other";  // other
export * from "./validate-schema_dashboard";  // dashboard

// Original file backed up to:
//   /Users/fredbook/.snackbar/backups/file-splitter/20260618_220203_validate-schema.js