"""test_cpu — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215854

"""Verifies that the processor class works as expected."""

import sys
from random import choice

import pytest

from m6502 import Memory, Processor

# Opcodes for the 6502 processor.

from test_cpu_other import *  # other

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215854_test_cpu.py