"""dashboard module — extracted from engine.py"""
# Auto-generated by file-splitter on 20260618_215755

"""
Export Engine — core logic for static HTML generation.

Supports three export formats:
- FULL_SITE: Complete HTML page with theme, navigation, widgets
- SINGLE_PAGE: Minimal standalone HTML for a single component
- WIDGET: Embeddable HTML snippet
"""

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional
import json
import os
import shutil




    def _widgets_script(self) -> str:
        """Generate widget initialization script."""
        return """
<script>
  document.addEventListener('DOMContentLoaded', function() {
    if (typeof uDosWidgets !== 'undefined') {
      uDosWidgets.refreshAll();
    }
  });
</script>"""

    def _read_asset(self, path: str) -> Optional[str]:
        """Read a theme asset file."""
        asset_path = self._themes_dir / path
        if asset_path.is_file():
            try:
                return asset_path.read_text()
            except Exception:
                return None
        return None

    def _write_output(self, slug: str, html: str) -> str:
        """Write HTML to the output directory."""
        output_dir = Path(self.options.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{slug}.html"
        filepath = output_dir / filename
        filepath.write_text(html)

        # Copy theme assets if requested
        if self.options.copy_assets:
            self._copy_assets(output_dir)

        return str(filepath)

    def _copy_assets(self, output_dir: Path) -> None:
        """Copy theme assets to the output directory."""
        assets_dir = output_dir / "assets"
        assets_dir.mkdir(exist_ok=True)

        # Copy CSS files
        for css_file in ["display.css", "tailwind.css"]:
            src = self._themes_dir / css_file
            if src.is_file():
                shutil.copy2(src, assets_dir / css_file)

        # Copy theme-specific assets
        theme = self.options.theme
        theme_dir = self._themes_dir / theme
        if theme_dir.is_dir():
            theme_assets = assets_dir / theme
            theme_assets.mkdir(exist_ok=True)
            for item in theme_dir.iterdir():
                if item.is_file() and item.suffix in (".css", ".js", ".woff", ".woff2", ".ttf", ".eot", ".png"):
                    shutil.copy2(item, theme_assets / item.name)

    @staticmethod
    def _escape_html(text: str) -> str:
        """Escape HTML special characters."""
        return (
            text.replace("&", "&")
            .replace("<", "<")
            .replace(">", ">")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )

