"""engine — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215755

"""
Export Engine — core logic for static HTML generation.

Supports three export formats:
- FULL_SITE: Complete HTML page with theme, navigation, widgets
- SINGLE_PAGE: Minimal standalone HTML for a single component
- WIDGET: Embeddable HTML snippet
"""

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional
import json
import os
import shutil



from .engine_other import *  # other
from engine_snacks import *  # snacks
from engine_dashboard import *  # dashboard

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215755_engine.py