import { describe, expect, it } from 'vitest'
import { mkdtempSync, rmSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { skinWeaver, writeSkinManifest } from '../src/tools/skin-weaver'

const TEST_DIR = mkdtempSync(join(tmpdir(), 'gridsmith-skin-weaver-'))

describe('SKIN-Weaver', () => {
  it('generates skin manifest from assets', () => {
    const result = skinWeaver({
      source_assets: [
        { path: 'gfx/sprites/ship.png', type: 'sprite_data' },
        { path: 'gfx/maps/level1.bin', type: 'map_data' },
        { path: 'text/intro.txt', type: 'teletext_pages' },
      ],
      target: {
        locale: 'teletext_grid',
        resolution: { cols: 40, rows: 25 },
        palette: 'bbc_mode7',
      },
    })

    expect(result.skill).toBe('SKIN-Weaver')
    expect(result.version).toBe('1.0')
    expect(result.skin_name).toBeTruthy()
    expect(result.manifest.name).toBeTruthy()
    expect(result.manifest.palette).toBeDefined()
    expect(result.manifest.character_mappings.length).toBeGreaterThan(0)
    expect(result.exported_assets.length).toBe(3)
  })

  it('assigns correct character mapping by asset type', () => {
    const result = skinWeaver({
      source_assets: [
        { path: 'ship.bin', type: 'sprite_data' },
        { path: 'map.bin', type: 'map_data' },
        { path: 'sound.wav', type: 'audio_data' },
      ],
      target: {
        locale: 'teletext_grid',
        resolution: { cols: 40, rows: 25 },
        palette: 'bbc_mode7',
      },
    })

    const spriteMap = result.manifest.character_mappings.find((m) => m.source === 'ship.bin')
    expect(spriteMap).toBeDefined()
    expect(spriteMap?.target_char).toBe('*')
    expect(spriteMap?.target_fg).toBe(3)

    const mapMap = result.manifest.character_mappings.find((m) => m.source === 'map.bin')
    expect(mapMap).toBeDefined()
    expect(mapMap?.target_char).toBe('#')
    expect(mapMap?.target_fg).toBe(6)

    const audioMap = result.manifest.character_mappings.find((m) => m.source === 'sound.wav')
    expect(audioMap).toBeDefined()
    expect(audioMap?.target_char).toBe('~')
    expect(audioMap?.target_fg).toBe(5)
  })

  it('supports multiple palettes', () => {
    const result = skinWeaver({
      source_assets: [{ path: 'ship.bin', type: 'sprite_data' }],
      target: {
        locale: 'teletext',
        resolution: { cols: 40, rows: 25 },
        palette: 'dark_fantasy',
      },
    })

    expect(result.manifest.palette['1']).toBe('#8b0000')
    expect(result.manifest.palette['0']).toBe('#0a0a0a')
  })

  it('uses default bbc_mode7 palette for unknown palette name', () => {
    const result = skinWeaver({
      source_assets: [{ path: 'test.bin', type: 'game_data' }],
      target: {
        locale: 'teletext',
        resolution: { cols: 40, rows: 25 },
        palette: 'nonexistent_palette',
      },
    })

    expect(result.manifest.palette['1']).toBe('#ff0000') // bbc_mode7 red
  })

  it('generates teletext row overrides', () => {
    const result = skinWeaver({
      source_assets: [{ path: 'test.bin', type: 'sprite_data' }],
      target: {
        locale: 'teletext_grid',
        resolution: { cols: 40, rows: 25 },
        palette: 'bbc_mode7',
      },
    })

    expect(result.manifest.teletext_overrides.header_row).toBeDefined()
    expect(result.manifest.teletext_overrides.header_row?.fg).toBe(2)
    expect(result.manifest.teletext_overrides.header_row?.bold).toBe(true)

    expect(result.manifest.teletext_overrides.hud_row).toBeDefined()
    expect(result.manifest.teletext_overrides.alert_row).toBeDefined()
  })

  it('writes YAML manifest to disk', () => {
    const result = skinWeaver({
      source_assets: [{ path: 'test.bin', type: 'sprite_data' }],
      target: {
        locale: 'teletext_grid',
        resolution: { cols: 40, rows: 25 },
        palette: 'bbc_mode7',
      },
    })

    const outDir = join(TEST_DIR, 'skins')
    const writtenPath = writeSkinManifest(result, outDir, 'yaml')

    expect(writtenPath).toMatch(/\.skin\.yaml$/)
    const content = readFileSync(writtenPath, 'utf-8')
    expect(content).toMatch(/# Auto-generated by SKIN-Weaver/)
    expect(content).toMatch(/palette:/)
    expect(content).toMatch(/character_mappings:/)
    expect(content).toMatch(/teletext_overrides:/)
  })

  it('writes JSON manifest to disk', () => {
    const result = skinWeaver({
      source_assets: [{ path: 'test.bin', type: 'sprite_data' }],
      target: {
        locale: 'teletext_grid',
        resolution: { cols: 40, rows: 25 },
        palette: 'bbc_mode7',
      },
    })

    const outDir = join(TEST_DIR, 'skins_json')
    const jsonPath = writeSkinManifest(result, outDir, 'json')

    expect(jsonPath).toMatch(/\.skin\.json$/)
    const content = readFileSync(jsonPath, 'utf-8')
    const parsed = JSON.parse(content)
    expect(parsed.generated_by).toBe('SKIN-Weaver v1.0')
    expect(parsed.skin.name).toBeTruthy()
    expect(parsed.palette).toBeDefined()
  })

  it('deduplicates character mappings', () => {
    const result = skinWeaver({
      source_assets: [
        { path: 'a.bin', type: 'sprite_data' },
        { path: 'b.bin', type: 'sprite_data' },
        { path: 'c.bin', type: 'sprite_data' },
      ],
      target: {
        locale: 'teletext_grid',
        resolution: { cols: 40, rows: 25 },
        palette: 'bbc_mode7',
      },
    })

    // All three are sprite_data, should map to same char '*' with fg=3
    // Dedupe should collapse them to 1 mapping
    expect(result.manifest.character_mappings.length).toBe(1)

    // But exported_assets should still have 3 entries
    expect(result.exported_assets.length).toBe(3)
  })

  // Cleanup
  try { rmSync(TEST_DIR, { recursive: true, force: true }) } catch { /* ok */ }
})