"""acs_cli — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215559

"""
ACS CLI — Command-line interface for the ACS Emulator

Usage:
  ucode acs [COMMAND] [OPTIONS]

Commands:
  run          Run an ACS game from a disk image
  step         Single-step through execution
  state        Show current emulator state
  reset        Reset the emulator
  load-rom     Load a ROM file
  load-disk    Load a disk image
  debug        Start interactive debugger
  mcp          Send MCP commands to the emulator
  info         Show emulator information
  save-state   Save emulator state to file
  load-state   Load emulator state from file
  key          Send a key press to the emulator
  type         Type text into the emulator
  export       Export display to HTML/ANSI/JSON
  help         Show help for a command

Examples:
  ucode acs load-rom apple2.rom
  ucode acs load-disk mygame.dsk
  ucode acs run --max-instructions 10000
  ucode acs step
  ucode acs state
  ucode acs key 65          # Press 'A'
  ucode acs type "HELLO"
  ucode acs export --format html
  ucode acs mcp send PAUSE
  ucode acs debug
"""

import sys
import os
import json
import argparse
import time
from pathlib import Path
from typing import Optional, Dict, Any

# Add core_py to path

from .acs_cli_other import *  # other
from acs_cli_mcp import *  # mcp

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215559_acs_cli.py