"""mcp module — extracted from acs_cli.py"""
# Auto-generated by file-splitter on 20260618_215559

"""
ACS CLI — Command-line interface for the ACS Emulator

Usage:
  ucode acs [COMMAND] [OPTIONS]

Commands:
  run          Run an ACS game from a disk image
  step         Single-step through execution
  state        Show current emulator state
  reset        Reset the emulator
  load-rom     Load a ROM file
  load-disk    Load a disk image
  debug        Start interactive debugger
  mcp          Send MCP commands to the emulator
  info         Show emulator information
  save-state   Save emulator state to file
  load-state   Load emulator state from file
  key          Send a key press to the emulator
  type         Type text into the emulator
  export       Export display to HTML/ANSI/JSON
  help         Show help for a command

Examples:
  ucode acs load-rom apple2.rom
  ucode acs load-disk mygame.dsk
  ucode acs run --max-instructions 10000
  ucode acs step
  ucode acs state
  ucode acs key 65          # Press 'A'
  ucode acs type "HELLO"
  ucode acs export --format html
  ucode acs mcp send PAUSE
  ucode acs debug
"""

import sys
import os
import json
import argparse
import time
from pathlib import Path
from typing import Optional, Dict, Any

# Add core_py to path


    def _command_mcp(self, args):
        """Send MCP commands to the emulator.

        Usage: ucode acs mcp <subcommand> [OPTIONS]

        Subcommands:
          send COMMAND [ARGS]    Send an MCP command
          status                 Show MCP state
          history                Show command history
          clear                  Clear pending commands

        Commands:
          PAUSE       Pause execution
          RESUME      Resume execution
          SAVE        Save state
          RESTORE     Restore state
          INSPECT var Inspect a variable
          EVAL expr   Evaluate an expression
          QUIT        Quit the emulator
          STEP        Single step
          RESET       Reset the emulator
          STATE       Show CPU state
        """
        if len(args) < 1:
            print("Usage: ucode acs mcp <subcommand> [OPTIONS]")
            print("Subcommands: send, status, history, clear")
            return

        from core_py.bbc.mcp_bridge import create_mcp_bridge
        mcp = create_mcp_bridge()

        subcommand = args[0]
        sub_args = args[1:]

        if subcommand == "send":
            if len(sub_args) < 1:
                print("Usage: ucode acs mcp send COMMAND [ARGS]")
                print("Commands: PAUSE, RESUME, SAVE, RESTORE, INSPECT, EVAL, QUIT, STEP, RESET, STATE")
                return
            cmd_str = " ".join(sub_args)
            cmd = mcp.queue_command(cmd_str, source="cli")
            response = mcp.process_command(cmd)
            if response:
                print(f"✅ {response}")
            else:
                print(f"✅ Command queued: {cmd_str}")

        elif subcommand == "status":
            state = mcp.get_state() if hasattr(mcp, 'get_state') else {}
            print("MCP State:")
            print(f"  Enabled: {mcp._enabled}")
            print(f"  Pending commands: {len(mcp._pending_commands)}")
            print(f"  Pending responses: {len(mcp._responses)}")

        elif subcommand == "history":
            print("Command history not available in basic mode")

        elif subcommand == "clear":
            mcp.clear_commands()
            mcp.clear_responses()
            print("✅ Cleared pending commands and responses")

        else:
            print(f"Unknown mcp subcommand: {subcommand}")

    # ── Info ────────────────────────────────────────────────────────

    def _command_info(self, args):
        """Show emulator information.

        Usage: ucode acs info [OPTIONS]

        Options:
          --json    Output as JSON
        """
        parser = argparse.ArgumentParser(description="Show emulator info")
        parser.add_argument("--json", action="store_true",
                          help="Output as JSON")

        try:
            parsed = parser.parse_args(args)
        except SystemExit:
            return

        info = self.emulator.get_info()

        if parsed.json:
            print(json.dumps(info, indent=2))
            return

        print("ACS Emulator Info:")
        print(f"  Running: {info['running']}")
        print(f"  Paused: {info['paused']}")
        print(f"  Instructions: {info['instructions']}")
        print(f"  Elapsed: {info['elapsed']:.2f}s")
        print(f"  IPS: {info['ips']:.0f}")
        print(f"  CPU: PC=0x{info['cpu']['pc']:04X}")
        print(f"  Disk loaded: {info['disk'] is not None}")
        print(f"  Debugger: {info['debugger']}")

    # ── Save/Load State ─────────────────────────────────────────────

    def _command_save_state(self, args):
        """Save emulator state to file.

        Usage: ucode acs save-state [OPTIONS] FILE
        """
        parser = argparse.ArgumentParser(description="Save emulator state")
        parser.add_argument("file", help="Output file path")

        try:
            parsed = parser.parse_args(args)
        except SystemExit:
            return

        state = self.emulator.save_state()
        try:
            with open(parsed.file, 'w') as f:
                json.dump(state, f, indent=2, default=str)
            print(f"✅ State saved to: {parsed.file}")
        except Exception as e:
            print(f"❌ Error saving state: {e}")

    def _command_load_state(self, args):
        """Load emulator state from file.

        Usage: ucode acs load-state [OPTIONS] FILE
        """
        parser = argparse.ArgumentParser(description="Load emulator state")
        parser.add_argument("file", help="Input file path")

        try:
            parsed = parser.parse_args(args)
        except SystemExit:
            return

        path = Path(parsed.file)
        if not path.exists():
            print(f"❌ State file not found: {parsed.file}")
            return

        try:
            with open(path, 'r') as f:
                state = json.load(f)
            self.emulator.restore_state(state)
            print(f"✅ State loaded from: {parsed.file}")
        except Exception as e:
            print(f"❌ Error loading state: {e}")

    # ── Key / Type ──────────────────────────────────────────────────

    def _command_key(self, args):
        """Send a key press to the emulator.

        Usage: ucode acs key [OPTIONS] KEYCODE

        Options:
          --char    Interpret argument as a character instead of keycode
        """
        parser = argparse.ArgumentParser(description="Send a key press")
        parser.add_argument("key", help="Key code (numeric) or character (with --char)")
        parser.add_argument("--char", action="store_true",
                          help="Interpret as character")

        try:
            parsed = parser.parse_args(args)
        except SystemExit:
            return

        if parsed.char:
            key = ord(parsed.key.upper())
        else:
            try:
                key = int(parsed.key, 0)
            except ValueError:
                print(f"❌ Invalid key code: {parsed.key}")
                return

        self.emulator.io.key_press(key)
        char = chr(key) if 32 <= key <= 126 else f"0x{key:02X}"
        print(f"✅ Key pressed: {char}")

    def _command_type(self, args):
        """Type text into the emulator.

        Usage: ucode acs type [OPTIONS] TEXT
        """
        parser = argparse.ArgumentParser(description="Type text into emulator")
        parser.add_argument("text", nargs="+", help="Text to type")

        try:
            parsed = parser.parse_args(args)
        except SystemExit:
            return

        text = " ".join(parsed.text)
        self.emulator.io.type_string(text)
        print(f"✅ Typed: {text}")

    # ── Export ──────────────────────────────────────────────────────

    def _command_export(self, args):
        """Export display to HTML, ANSI, or JSON.

        Usage: ucode acs export [OPTIONS]

        Options:
          --format FORMAT    Export format: html, ansi, json (default: html)
          --output FILE      Output file path (default: stdout)
        """
        parser = argparse.ArgumentParser(description="Export display")
        parser.add_argument("--format", choices=["html", "ansi", "json"],
                          default="html", help="Export format (default: html)")
        parser.add_argument("--output", help="Output file path")

        try:
            parsed = parser.parse_args(args)
        except SystemExit:
            return

        display_text = self.emulator.io.get_display_text()

        if parsed.format == "json":
            output = json.dumps({
                "display": display_text,
                "mode": self.emulator.io.display.mode.name,
                "cpu": self.emulator.get_cpu_state(),
            }, indent=2)
        elif parsed.format == "ansi":
            # Simple ANSI rendering
            output = display_text
        else:
            # HTML
            escaped = display_text.replace("&", "&").replace("<", "<").replace(">", ">")
            output = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ACS Display</title>
    <style>
        body {{ background: #000; color: #0f0; font-family: monospace; padding: 2rem; }}
        pre {{ white-space: pre-wrap; }}
    </style>
</head>
<body>
    <pre>{escaped}</pre>
</body>
</html>"""

        if parsed.output:
            try:
                Path(parsed.output).write_text(output, encoding="utf-8")
                print(f"✅ Exported to: {parsed.output}")
            except Exception as e:
                print(f"❌ Error writing output: {e}")
        else:
            print(output)


def main():
    """Main entry point for ACS CLI"""
    cli = ACS_CLI()
    cli.main(sys.argv[1:])


if __name__ == "__main__":
    main()

