from __future__ import annotations

"""mcp module — extracted from task_mcp_server.py"""
# Auto-generated by file-splitter on 20260618_215834

#!/usr/bin/env python3
"""
MCP Server for task management tools.

Provides MCP tools:
  - task_list: List tasks in a lane (returns JSON feed)
  - task_create: Create a new task
  - task_update: Update any field on a task
  - task_kanban_board: Return Kanban board data

Run with: python task_mcp_server.py
Or via stdio: python task_mcp_server.py --stdio
"""


import json
import sys
import argparse
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

# Add parent directory to path for imports


def handle_mcp_request(request: dict) -> dict:
    """Handle a JSON-RPC MCP request."""
    method = request.get("method", "")
    params = request.get("params", {})

    if method == "tools/list":
        return {
            "tools": [
                {
                    "name": name,
                    "description": info["description"],
                    "inputSchema": info["input_schema"],
                }
                for name, info in TOOLS.items()
            ]
        }

    if method == "tools/call":
        tool_name = params.get("name", "")
        tool_args = params.get("arguments", {})
        tool = TOOLS.get(tool_name)
        if not tool:
            return {"error": f"Unknown tool: {tool_name}"}
        result = tool["handler"](tool_args)
        return {"content": [{"type": "text", "text": json.dumps(result, indent=2)}]}

    return {"error": f"Unknown method: {method}"}


def run_stdio():
    """Run MCP server over stdio (for DevStudio integration)."""
    import sys
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
            response = handle_mcp_request(request)
            print(json.dumps(response))
            sys.stdout.flush()
        except json.JSONDecodeError as e:
            print(json.dumps({"error": f"Invalid JSON: {e}"}))
            sys.stdout.flush()


def run_http(port: int = 30001):
    """Run MCP server over HTTP."""
    from http.server import HTTPServer, BaseHTTPRequestHandler

    class MCPHandler(BaseHTTPRequestHandler):
        def do_POST(self):
            content_length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(content_length)
            try:
                request = json.loads(body)
                response = handle_mcp_request(request)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps(response).encode())
            except Exception as e:
                self.send_response(500)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"error": str(e)}).encode())

        def do_GET(self):
            if self.path == "/health":
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"status": "ok", "tools": list(TOOLS.keys())}).encode())
                return
            self.send_response(404)
            self.end_headers()

        def log_message(self, format, *args):
            pass  # Suppress HTTP logs

    server = HTTPServer(("0.0.0.0", port), MCPHandler)
    print(f"🧠 Task MCP Server running on http://localhost:{port}")
    print(f"   Tools: {', '.join(TOOLS.keys())}")
    server.serve_forever()


def main():
    parser = argparse.ArgumentParser(description="Task MCP Server")
    parser.add_argument("--stdio", action="store_true", help="Run over stdio")
    parser.add_argument("--port", type=int, default=30001, help="HTTP port (default: 30001)")
    args = parser.parse_args()

    if args.stdio:
        run_stdio()
    else:
        run_http(args.port)


if __name__ == "__main__":
    main()

