"""task_mcp_server — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215834

#!/usr/bin/env python3
"""
MCP Server for task management tools.

Provides MCP tools:
  - task_list: List tasks in a lane (returns JSON feed)
  - task_create: Create a new task
  - task_update: Update any field on a task
  - task_kanban_board: Return Kanban board data

Run with: python task_mcp_server.py
Or via stdio: python task_mcp_server.py --stdio
"""

from __future__ import annotations

import json
import sys
import argparse
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

# Add parent directory to path for imports

from task_mcp_server_scheduler import *  # scheduler
from task_mcp_server_other import *  # other
from task_mcp_server_dashboard import *  # dashboard
from task_mcp_server_health import *  # health
from task_mcp_server_mcp import *  # mcp

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215834_task_mcp_server.py