"""test_rules_engine_integration — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215812

"""
Integration tests for the new Rules Engine with uHOME DVR system.

This test suite verifies that the new rules engine is properly integrated
with the existing uHOME infrastructure.
"""

import pytest
import json
import tempfile
from pathlib import Path
from datetime import datetime, timedelta
from fastapi.testclient import TestClient

from uhome_server.main import app
from uhome_server.services.rules_engine import (

from test_rules_engine_integration_other import *  # other
from test_rules_engine_integration_mission_control import *  # mission_control
from test_rules_engine_integration_health import *  # health

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215812_test_rules_engine_integration.py