"""health module — extracted from test_rules_engine_integration.py"""
# Auto-generated by file-splitter on 20260618_215812

"""
Integration tests for the new Rules Engine with uHOME DVR system.

This test suite verifies that the new rules engine is properly integrated
with the existing uHOME infrastructure.
"""

import pytest
import json
import tempfile
from pathlib import Path
from datetime import datetime, timedelta
from fastapi.testclient import TestClient

from uhome_server.main import app
from uhome_server.services.rules_engine import (



def test_engine_status(rules_engine):
    """Test getting engine status."""
    # Create some test data
    rules_engine.create_rule({
        "rule_name": "Status Test Rule 1",
        "rule_type": RuleType.TIME_BASED.value,
        "channel_id": "channel_1",
        "start_time": "18:00:00",
        "end_time": "19:00:00",
        "enabled": True
    })
    
    rules_engine.create_rule({
        "rule_name": "Status Test Rule 2",
        "rule_type": RuleType.SERIES.value,
        "series_id": "series_1",
        "series_title": "Series 1",
        "enabled": False
    })
    
    # Get engine status
    status = rules_engine.get_engine_status()
    
    assert status["rules_count"] == 2
    assert status["active_rules"] == 1
    assert status["schedule_count"] == 0
    assert status["upcoming_executions"] == 0
    assert status["conflicts_detected"] == 0
    assert status["conflicts_resolved"] == 0
    assert status["execution_history_count"] == 0
    assert status["initialized"] is True


def test_performance_benchmarks(rules_engine, benchmark):
    """Test performance benchmarks for the rules engine."""
    # Create many rules for performance testing
    def create_many_rules():
        for i in range(100):
            rules_engine.create_rule({
                "rule_name": f"Performance Test Rule {i}",
                "rule_type": RuleType.TIME_BASED.value,
                "channel_id": f"channel_{i % 10}",
                "start_time": "18:00:00",
                "end_time": "19:00:00",
                "enabled": i % 2 == 0
            })
    
    # Benchmark rule creation
    benchmark(create_many_rules)
    
    # Benchmark rule listing
    def list_rules():
        return rules_engine.list_rules()
    
    benchmark(list_rules)
    
    # Benchmark rule retrieval
    def get_rules():
        for rule_id in list(rules_engine.rules.keys())[:10]:
            rules_engine.get_rule(rule_id)
    
    benchmark(get_rules)


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])

