// ---------------------------------------------------------------------------
// Types (aligned with SKILLS_FRAMEWORK.md and The uCode-Weaver Skill)
// ---------------------------------------------------------------------------

import type { GameDesignDocument, CoreMechanic } from './inspire-engine'

export interface UCodeWeaverInput {
  gdd: GameDesignDocument
  program_name: string
  runtime: string
  display_mode: string
  entry_file?: string
}

export interface BbcBasicProcedure {
  name: string
  description: string
  body: string
}

export interface UCodeWeaverOutput {
  skill: 'uCode-Weaver'
  version: '1.0'
  executed_at: string
  program_name: string
  entry_file: string
  procedures: BbcBasicProcedure[]
  generated_code: string
  written_to?: string
}

// ---------------------------------------------------------------------------
// BBC BASIC code generation
// ---------------------------------------------------------------------------

function generateHeader(programName: string, runtime: string): string {
  const lines = [
    `   10 REM ====================================================`,
    `   20 REM ${programName} - uCode Adaptation`,
    `   30 REM BBC BASIC for SDL 2.0`,
    `   40 REM Generated by uCode-Weaver v1.0`,
    `   50 REM Runtime: ${runtime}`,
    `   60 REM ====================================================`,
  ]
  return lines.join('\n')
}

function generateConstants(gdd: GameDesignDocument): string {
  const lines: string[] = [
    '',
    `   70 REM ---- Game Constants ----`,
  ]

  // Generate from core mechanics
  for (const mech of gdd.core_mechanics) {
    if (mech.name === 'text_parser') {
      lines.push(`   80 MAX_VOCAB% = 200`)
      lines.push(`   90 MAX_VERBS% = 60`)
    }
    if (mech.name === 'npc_schedules') {
      lines.push(`  100 MAX_NPCS% = 10`)
      lines.push(`  110 TICKS_PER_DAY% = 24`)
    }
    if (mech.name === 'magic_system') {
      if (mech.spells) {
        lines.push(`  120 MAX_MANA% = 50`)
        lines.push(`  130 MAX_SPELLS% = ${mech.spells.length}`)
      }
    }
    if (mech.name === 'tile_editor') {
      lines.push(`   80 GRID_W% = 64`)
      lines.push(`   90 GRID_H% = 48`)
      lines.push(`  100 MAX_TILES% = 16`)
    }
    if (mech.name === 'digging_system') {
      lines.push(`   80 GRID_W% = 32`)
      lines.push(`   90 GRID_H% = 18`)
      lines.push(`  100 MAX_HOLES% = 3`)
      lines.push(`  110 MAX_LIVES% = 3`)
    }
  }

  return lines.join('\n')
}

function generateStateVariables(gdd: GameDesignDocument): string {
  const lines: string[] = [
    '',
    `  200 REM ---- Game State ----`,
    `  210 DIM score%(1)`,
    `  220 score%(0) = 0 : score%(1) = 0`,
  ]

  const integration = gdd.uCode_integration
  if (integration) {
    for (const target of integration.lens_extractors) {
      const name = target.target.toUpperCase() + '%'
      if (target.type === 'string') {
        lines.push(`  230 ${target.target}$ = ""`)
      } else if (target.type === 'uint8' || target.type === 'uint16' || target.type === 'uint32') {
        lines.push(`  230 ${name} = 0`)
      } else if (target.type === 'array') {
        lines.push(`  230 DIM ${name.replace('%','')}(9)`)
      }
    }
  }

  return lines.join('\n')
}

function generateMainLoop(procedures: BbcBasicProcedure[]): string {
  const lines = [
    '',
    `  400 REM ---- Main Loop ----`,
    `  410 PROCinit`,
    `  420 REPEAT`,
    `  430   PROCinput`,
    `  440   PROCupdate`,
    `  450   PROCrender`,
    `  460   IF FNgame_over THEN PROCgame_over`,
    `  470 UNTIL FALSE`,
    `  480 END`,
  ]
  return lines.join('\n')
}

function generateInit(mechanics: CoreMechanic[]): BbcBasicProcedure {
  const body = [
    `  510   CLS`,
    `  520   PRINT "Loading..."`,
    `  530   REM Initialize game state from LENS variables`,
  ]

  // Add mechanics-specific init
  for (const mech of mechanics) {
    if (mech.name === 'combat_system') {
      body.push(`  540   player_hp% = 30`)
      body.push(`  550   player_ac% = 10`)
    }
    if (mech.name === 'magic_system') {
      body.push(`  560   mana% = MAX_MANA%`)
    }
    if (mech.name === 'scoring') {
      body.push(`  570   score%(0) = 0 : score%(1) = 0`)
    }
  }

  body.push(`  580 ENDPROC`)

  return {
    name: 'PROCinit',
    description: 'Initialize game state',
    body: body.join('\n'),
  }
}

function generateInput(mechanics: CoreMechanic[]): BbcBasicProcedure {
  const isTextAdventure = mechanics.some(m => m.name === 'text_parser')
  const isPlatformer = mechanics.some(m => m.name === 'digging_system' || m.name === 'ladder_movement')

  if (isTextAdventure) {
    return {
      name: 'PROCinput',
      description: 'Handle text parser input',
      body: [
        `  610   LOCAL K$`,
        `  620   INPUT "> " K$`,
        `  630   K$ = FNupper$(K$)`,
        `  640   PROCparse_command(K$)`,
        `  650 ENDPROC`
      ].join('\n'),
    }
  }

  if (isPlatformer) {
    return {
      name: 'PROCinput',
      description: 'Handle keyboard input for movement and actions',
      body: [
        `  610   LOCAL K%`,
        `  620   K% = INKEY(0)`,
        `  630   IF K% = 138 THEN pd% = 0 : ENDPROC`,
        `  640   IF K% = 139 THEN pd% = 1 : ENDPROC`,
        `  650   IF K% = 140 THEN pd% = 2 : ENDPROC`,
        `  660   IF K% = 137 THEN pd% = 3 : ENDPROC`,
        `  670   IF K% = 32 THEN PROCaction : ENDPROC`,
        `  680 ENDPROC`
      ].join('\n'),
    }
  }

  // Default: construction/builder
  return {
    name: 'PROCinput',
    description: 'Handle cursor-based input',
    body: [
      `  610   LOCAL K%`,
      `  620   K% = INKEY(0)`,
      `  630   IF K% = 138 THEN cy% = cy% - 1 : ENDPROC`,
      `  640   IF K% = 139 THEN cx% = cx% + 1 : ENDPROC`,
      `  650   IF K% = 140 THEN cy% = cy% + 1 : ENDPROC`,
      `  660   IF K% = 137 THEN cx% = cx% - 1 : ENDPROC`,
      `  670   IF K% = 32 THEN PROCplace_tile : ENDPROC`,
      `  680 ENDPROC`
    ].join('\n'),
  }
}

function generateUpdate(mechanics: CoreMechanic[]): BbcBasicProcedure {
  const hasEnemies = mechanics.some(m => m.name === 'enemy_ai' || m.name === 'combat_system')
  const hasNpcs = mechanics.some(m => m.name === 'npc_schedules')
  const hasTimer = mechanics.some(m => m.name === 'digging_system')

  const body = [
    `  710   REM Main update loop`,
  ]

  if (hasEnemies) {
    body.push(`  720   PROCmove_enemies`)
  }
  if (hasNpcs) {
    body.push(`  730   PROCupdate_npcs`)
  }
  if (hasTimer) {
    body.push(`  740   PROCupdate_timers`)
  }
  body.push(`  750 ENDPROC`)

  return {
    name: 'PROCupdate',
    description: 'Update game state each frame',
    body: body.join('\n'),
  }
}

function generateRender(mechanics: CoreMechanic[]): BbcBasicProcedure {
  const isTeletext = true // All uCode programs default to teletext
  const hasLocations = mechanics.some(m => m.name === 'world_model')

  const body = [
    `  810   LOCAL x%, y%`,
    `  820   CLS`,
  ]

  if (hasLocations) {
    const location = mechanics.find(m => m.name === 'world_model')
    const firstLoc = location?.locations?.[0]
    body.push(`  830   PRINT "Location: ${firstLoc?.name || 'Unknown'}"`)
    body.push(`  840   PRINT "Exits: ${firstLoc?.exits?.join(', ') || 'none'}"`)
    body.push(`  850   PRINT`)
  } else {
    body.push(`  830   REM Render grid-based display`)
    body.push(`  840   FOR y% = 0 TO 23`)
    body.push(`  850     FOR x% = 0 TO 39`)
    body.push(`  860       PRINT ".";`)
    body.push(`  870     NEXT`)
    body.push(`  880     PRINT`)
    body.push(`  890   NEXT`)
  }

  body.push(`  910   PRINT "Score: "; score%(1) * 256 + score%(0)`)
  body.push(`  920 ENDPROC`)

  return {
    name: 'PROCrender',
    description: 'Render the display',
    body: body.join('\n'),
  }
}

function generateStub(name: string, description: string): BbcBasicProcedure {
  return {
    name,
    description,
    body: [
      `  REM ${description}`,
      `  REM TODO: Implement ${name.toLowerCase()}`,
      `ENDPROC`,
    ].join('\n'),
  }
}

function generateProcedures(gdd: GameDesignDocument): BbcBasicProcedure[] {
  const mechanics = gdd.core_mechanics
  const procs: BbcBasicProcedure[] = []

  procs.push(generateInit(mechanics))
  procs.push(generateInput(mechanics))
  procs.push(generateUpdate(mechanics))
  procs.push(generateRender(mechanics))

  // Add game-over and helper stubs
  procs.push({
    name: 'FNgame_over',
    description: 'Check if game is over',
    body: [
      `   REM Check lives or completion condition`,
      `   = FALSE`,
    ].join('\n'),
  })

  procs.push({
    name: 'PROCgame_over',
    description: 'Handle game over sequence',
    body: [
      `   CLS`,
      `   PRINT "GAME OVER"`,
      `   PRINT "Score: "; score%(1) * 256 + score%(0)`,
      `   END`,
      `ENDPROC`,
    ].join('\n'),
  })

  procs.push({
    name: 'FNupper$',
    description: 'Convert string to uppercase',
    body: [
      `   LOCAL i%, c%, s$`,
      `   s$ = ""`,
      `   FOR i% = 1 TO LEN(K$)`,
      `     c% = ASC(MID$(K$, i%, 1))`,
      `     IF c% >= 97 AND c% <= 122 THEN c% = c% - 32`,
      `     s$ = s$ + CHR$(c%)`,
      `   NEXT`,
      `   = s$`,
    ].join('\n'),
  })

  return procs
}

function generateBBCBasic(gdd: GameDesignDocument, programName: string, runtime: string): BbcBasicProcedure[] {
  const procs = generateProcedures(gdd)
  return procs
}

// ---------------------------------------------------------------------------
// Simplified code generation (readable BBC BASIC)
// ---------------------------------------------------------------------------

function generateCode(
  gdd: GameDesignDocument,
  programName: string,
  runtime: string,
): string {
  const mechanics = gdd.core_mechanics
  const isText = mechanics.some(m => m.name === 'text_parser')
  const isPlatformer = mechanics.some(m => m.name === 'digging_system')

  const lines: string[] = []
  lines.push(`   10 REM ====================================================`)
  lines.push(`   20 REM ${programName} - uCode Adaptation`)
  lines.push(`   30 REM BBC BASIC for SDL 2.0 (Generated by uCode-Weaver v1.0)`)
  lines.push(`   40 REM Runtime: ${runtime}`)
  lines.push(`   50 REM Genre: ${gdd.genre.join(', ')}`)
  lines.push(`   60 REM ====================================================`)
  lines.push('')

  // Global state from uCode integration spec
  const integr = gdd.uCode_integration
  let lineNum = 100
  lines.push(`  ${lineNum} REM ---- Global State (LENS-extractable) ----`)
  lineNum += 10
  for (const lens of integr?.lens_extractors || []) {
    const n = lens.target
    if (lens.type === 'string') {
      lines.push(`  ${lineNum} ${n}$ = ""`)
    } else if (lens.type === 'array') {
      lines.push(`  ${lineNum} DIM ${n}(10)`)
    } else {
      lines.push(`  ${lineNum} ${n}% = 0`)
    }
    lineNum += 10
  }

  // Entry point
  lines.push('')
  lines.push(`  ${lineNum} REM ---- Entry Point ----`)
  lineNum += 10
  lines.push(`  ${lineNum} PROCinit`)
  lineNum += 10
  lines.push(`  ${lineNum} REPEAT`)
  lineNum += 10
  lines.push(`  ${lineNum}   IF FNgame_over THEN PROCgame_over`)
  lineNum += 10
  lines.push(`  ${lineNum}   PROCinput`)
  lineNum += 10
  lines.push(`  ${lineNum}   PROCupdate`)
  lineNum += 10
  lines.push(`  ${lineNum}   PROCrender`)
  lineNum += 10
  lines.push(`  ${lineNum} UNTIL FALSE`)
  lineNum += 10
  lines.push(`  ${lineNum} END`)
  lineNum += 10

  // PROCinit
  lines.push('')
  lines.push(`  ${lineNum} DEF PROCinit`)
  lineNum += 10
  lines.push(`  ${lineNum}   CLS : REM Initialize display`)
  lineNum += 10
  lines.push(`  ${lineNum} ENDPROC`)

  // FNgame_over
  lineNum += 10
  lines.push('')
  lines.push(`  ${lineNum} DEF FNgame_over`)
  lineNum += 10
  lines.push(`  ${lineNum}   REM Check win/lose conditions`)
  lineNum += 10
  lines.push(`  ${lineNum}   = FALSE`)
  lineNum += 10

  // PROCinput
  lines.push('')
  lines.push(`  ${lineNum} DEF PROCinput`)
  lineNum += 10
  lines.push(`  ${lineNum}   LOCAL K$`)
  lineNum += 10
  if (isText) {
    lines.push(`  ${lineNum}   INPUT "> " K$`)
    lineNum += 10
    lines.push(`  ${lineNum}   K$ = FNupper$(K$)`)
    lineNum += 10
    lines.push(`  ${lineNum}   PROCparse_command(K$)`)
  } else if (isPlatformer) {
    lines.push(`  ${lineNum}   K% = INKEY(0)`)
    lineNum += 10
    lines.push(`  ${lineNum}   IF K% = 138 THEN pd% = 0 : ENDPROC : REM Up`)
    lineNum += 10
    lines.push(`  ${lineNum}   IF K% = 139 THEN pd% = 1 : ENDPROC : REM Right`)
    lineNum += 10
    lines.push(`  ${lineNum}   IF K% = 140 THEN pd% = 2 : ENDPROC : REM Down`)
    lineNum += 10
    lines.push(`  ${lineNum}   IF K% = 137 THEN pd% = 3 : ENDPROC : REM Left`)
    lineNum += 10
    lines.push(`  ${lineNum}   IF K% = 32 THEN PROCaction : ENDPROC : REM Space`)
  } else {
    lines.push(`  ${lineNum}   K% = INKEY(0)`)
    lineNum += 10
    lines.push(`  ${lineNum}   REM Handle input`)
  }
  lineNum += 10
  lines.push(`  ${lineNum} ENDPROC`)

  // PROCupdate
  lineNum += 10
  lines.push('')
  lines.push(`  ${lineNum} DEF PROCupdate`)
  lineNum += 10
  lines.push(`  ${lineNum}   REM Update game state each frame`)
  lineNum += 10
  lines.push(`  ${lineNum} ENDPROC`)

  // PROCrender
  lineNum += 10
  lines.push('')
  lines.push(`  ${lineNum} DEF PROCrender`)
  lineNum += 10
  lines.push(`  ${lineNum}   CLS`)
  lineNum += 10
  lines.push(`  ${lineNum}   PRINT "Score: 0"`)
  lineNum += 10
  lines.push(`  ${lineNum} ENDPROC`)

  // PROCgame_over
  lineNum += 10
  lines.push('')
  lines.push(`  ${lineNum} DEF PROCgame_over`)
  lineNum += 10
  lines.push(`  ${lineNum}   CLS`)
  lineNum += 10
  lines.push(`  ${lineNum}   PRINT "GAME OVER"`)
  lineNum += 10
  lines.push(`  ${lineNum}   END`)
  lineNum += 10
  lines.push(`  ${lineNum} ENDPROC`)

  // FNupper$ helper for text adventures
  if (isText) {
    lineNum += 10
    lines.push('')
    lines.push(`  ${lineNum} DEF FNupper$(s$)`)
    lineNum += 10
    lines.push(`  ${lineNum}   LOCAL i%, c%, r$`)
    lineNum += 10
    lines.push(`  ${lineNum}   r$ = ""`)
    lineNum += 10
    lines.push(`  ${lineNum}   FOR i% = 1 TO LEN(s$)`)
    lineNum += 10
    lines.push(`  ${lineNum}     c% = ASC(MID$(s$, i%, 1))`)
    lineNum += 10
    lines.push(`  ${lineNum}     IF c% >= 97 AND c% <= 122 THEN c% = c% - 32`)
    lineNum += 10
    lines.push(`  ${lineNum}     r$ = r$ + CHR$(c%)`)
    lineNum += 10
    lines.push(`  ${lineNum}   NEXT`)
    lineNum += 10
    lines.push(`  ${lineNum}   = r$`)
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Main uCode-Weaver entry point
// ---------------------------------------------------------------------------

export function ucodeWeaver(input: UCodeWeaverInput): UCodeWeaverOutput {
  const entry = input.entry_file || `${input.program_name.toLowerCase().replace(/[^a-z]/g, '_')}.bbc`

  const procedures = generateBBCBasic(input.gdd, input.program_name, input.runtime)
  const generatedCode = generateCode(input.gdd, input.program_name, input.runtime)

  return {
    skill: 'uCode-Weaver',
    version: '1.0',
    executed_at: new Date().toISOString(),
    program_name: input.program_name,
    entry_file: entry,
    procedures,
    generated_code: generatedCode,
  }
}