"""events module — extracted from test_integration.py"""
# Auto-generated by file-splitter on 20260618_215818

"""
Integration tests for the full binder workflow pipeline.

Tests the complete flow:
  1. Create a task → file written to ~/Vault/binder/#tasks/
  2. Update task status → file updated
  3. Generate feeds → JSON written to ~/uDos/shared/feeds/
  4. MCP server serves feeds → binder_feed tool returns correct data
  5. Cross-lane webhook → GitHub PR merge triggers task status change

These tests use temporary directories to avoid touching real data.
"""

import json
import os
import sys
import tempfile
from pathlib import Path
from datetime import date
from unittest.mock import patch

import pytest

# Add project root to path


    def test_unhandled_event(self, temp_dirs):
        """Unhandled events should return an error."""
        result = handle_github_webhook({
            "event": "issues",
            "payload": {"action": "opened"},
        })
        assert result["success"] is False
        assert "Unhandled" in result["error"]


# ─── Test 4: MCP Protocol ─────────────────────────────────────────────────────

class TestMCPProtocol:
    """Test the JSON-RPC MCP protocol handler."""

    def test_tools_list(self, temp_dirs):
        """tools/list should return all registered tools."""
        response = handle_mcp_request({"method": "tools/list"})
        assert "tools" in response
        tool_names = [t["name"] for t in response["tools"]]
        assert "task_list" in tool_names
        assert "task_create" in tool_names
        assert "task_update" in tool_names
        assert "task_kanban_board" in tool_names
        assert "binder_feed" in tool_names
        assert "binder_list" in tool_names
        assert "binder_feed_update" in tool_names
        assert "github_webhook" in tool_names

    def test_tools_call(self, temp_dirs):
        """tools/call should invoke the correct tool."""
        response = handle_mcp_request({
            "method": "tools/call",
            "params": {
                "name": "binder_list",
                "arguments": {},
            },
        })
        assert "content" in response
        content = json.loads(response["content"][0]["text"])
        assert content["success"] is True

    def test_unknown_tool(self, temp_dirs):
        """Unknown tools should return an error."""
        response = handle_mcp_request({
            "method": "tools/call",
            "params": {
                "name": "nonexistent_tool",
                "arguments": {},
            },
        })
        assert "error" in response

    def test_unknown_method(self, temp_dirs):
        """Unknown methods should return an error."""
        response = handle_mcp_request({"method": "unknown/method"})
        assert "error" in response


# ─── Test 5: End-to-End Pipeline ──────────────────────────────────────────────

# ─── Sync Protocol Tests ──────────────────────────────────────────────────────

class TestSyncProtocol:
    """Tests for the cross-machine sync protocol (Phase D)."""

    def test_sync_to_sqlite_creates_db(self, temp_dirs):
        """sync_to_sqlite() should create a SQLite database."""
        from Usync.binder.task_models import sync_to_sqlite, SQLITE_DB
        create_task(title="Sync Test Task", lane="dev")
        sync_to_sqlite()
        assert SQLITE_DB.exists()
        # Verify data in SQLite
        import sqlite3
        conn = sqlite3.connect(str(SQLITE_DB))
        row = conn.execute("SELECT COUNT(*) FROM tasks").fetchone()
        conn.close()
        assert row[0] >= 1

    def test_query_sqlite_returns_results(self, temp_dirs):
        """query_sqlite() should return tasks from SQLite."""
        from Usync.binder.task_models import sync_to_sqlite, query_sqlite
        create_task(title="SQLite Query Test", lane="dev", priority="high")
        sync_to_sqlite()
        results = query_sqlite(lane="dev")
        assert len(results) >= 1
        assert any(r["title"] == "SQLite Query Test" for r in results)

    def test_query_sqlite_filters_by_status(self, temp_dirs):
        """query_sqlite() should filter by status."""
        from Usync.binder.task_models import sync_to_sqlite, query_sqlite
        t1 = create_task(title="Status Filter A", lane="dev")
        t2 = create_task(title="Status Filter B", lane="dev")
        update_task(t1.task_id, "status", "in-progress")
        sync_to_sqlite()
        backlog = query_sqlite(status="backlog")
        in_progress = query_sqlite(status="in-progress")
        assert len(backlog) >= 1
        assert len(in_progress) >= 1

    def test_get_sync_status(self, temp_dirs):
        """get_sync_status() should return sync metadata."""
        from Usync.binder.task_models import sync_to_sqlite, get_sync_status
        create_task(title="Sync Status Test", lane="dev")
        sync_to_sqlite()
        status = get_sync_status()
        assert status["db_exists"] is True
        assert status["task_count"] >= 1
        assert "dev" in status["tasks_per_lane"]

    def test_export_sync_payload(self, temp_dirs):
        """export_sync_payload() should return all tasks as portable JSON."""
        from Usync.binder.task_models import export_sync_payload
        create_task(title="Export Test Task", lane="dev", priority="urgent")
        payload = export_sync_payload()
        assert payload["version"] == "1.0"
        assert payload["protocol"] == "udos-task-sync"
        assert payload["task_count"] >= 1
        assert any(t["title"] == "Export Test Task" for t in payload["tasks"])

    def test_import_sync_payload(self, temp_dirs):
        """import_sync_payload() should create tasks from a payload."""
        from Usync.binder.task_models import import_sync_payload
        payload = {
            "version": "1.0",
            "protocol": "udos-task-sync",
            "task_count": 2,
            "tasks": [
                {"id": "imported-task-1", "title": "Imported Task 1", "lane": "dev", "status": "in-progress", "priority": "high"},
                {"id": "imported-task-2", "title": "Imported Task 2", "lane": "publishing", "status": "backlog", "priority": "medium"},
            ],
        }
        result = import_sync_payload(payload)
        assert result["imported"] == 2
        assert result["skipped"] == 0
        assert result["error_count"] == 0

    def test_import_skips_existing(self, temp_dirs):
        """import_sync_payload() should skip tasks that already exist."""
        from Usync.binder.task_models import import_sync_payload, create_task
        task = create_task(title="Existing Task", lane="dev")
        # Use the actual task ID so the file exists
        payload = {
            "version": "1.0",
            "protocol": "udos-task-sync",
            "task_count": 1,
            "tasks": [
                {"id": task.task_id, "title": "Existing Task", "lane": "dev", "status": "backlog"},
            ],
        }
        result = import_sync_payload(payload)
        assert result["imported"] == 0
        assert result["skipped"] == 1

    def test_sync_mcp_tools(self, temp_dirs):
        """MCP sync tools should work end-to-end."""
        from Usync.binder.task_mcp_server import (
            handle_sync_status,
            handle_sync_export,
            handle_sync_import,
            handle_query_sqlite,
        )
        from Usync.binder.task_models import sync_to_sqlite

        # Create a task and sync to SQLite
        create_task(title="MCP Sync Test", lane="dev", priority="high")
        sync_to_sqlite()

        # Test sync_status
        status_result = handle_sync_status({})
        assert status_result["success"] is True
        assert status_result["data"]["task_count"] >= 1

        # Test sync_export
        export_result = handle_sync_export({})
        assert export_result["success"] is True
        assert export_result["data"]["task_count"] >= 1

        # Test query_sqlite
        query_result = handle_query_sqlite({"lane": "dev"})
        assert query_result["success"] is True
        assert query_result["data"]["count"] >= 1

        # Test sync_import
        import_result = handle_sync_import({
            "payload": {
                "tasks": [
                    {"id": "mcp-import-test", "title": "MCP Imported", "lane": "user", "status": "backlog"},
                ],
            },
        })
        assert import_result["success"] is True
        assert import_result["data"]["imported"] == 1


class TestEndToEndPipeline:
    """Full end-to-end test: create → update → feed → MCP serve."""

    def test_full_pipeline(self, temp_dirs):
        """
        Complete workflow test:
          1. Create a dev task
          2. Move it to in-progress
          3. Move it to review
          4. Generate feeds
          5. Read feed via MCP tool
          6. Verify all steps
        """
        # Step 1: Create
        task = create_task(
            title="E2E Pipeline Test",
            lane="dev",
            description="End-to-end test task",
            priority="high",
            assignee="cline",
            tags=["e2e", "pipeline"],
        )
        assert task.path.exists()
        task_id = task.task_id

        # Step 2: Move to in-progress
        updated = update_task(task_id, "status", "in-progress")
        assert updated.frontmatter.status == TaskStatus.IN_PROGRESS

        # Step 3: Move to review
        updated = update_task(task_id, "status", "review")
        assert updated.frontmatter.status == TaskStatus.REVIEW

        # Step 4: Generate feeds
        write_feeds()
        feed_path = temp_dirs["feeds_dir"] / "tasks-dev.json"
        assert feed_path.exists()

        # Step 5: Read feed via MCP tool
        result = handle_binder_feed({"binder": "tasks-dev"})
        assert result["success"] is True
        assert len(result["data"]["cards"]) == 1
        card = result["data"]["cards"][0]
        assert card["title"] == "E2E Pipeline Test"
        assert card["status"] == "review"
        assert card["priority"] == "high"
        assert card["assignee"] == "cline"

        # Step 6: Verify Kanban board
        board = handle_task_kanban_board({"lane": "dev"})
        assert board["success"] is True
        assert len(board["data"]["cards"]["review"]) == 1
        assert len(board["data"]["cards"]["backlog"]) == 0
        assert len(board["data"]["cards"]["in-progress"]) == 0
        assert len(board["data"]["cards"]["done"]) == 0

