"""test_integration — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215818

"""
Integration tests for the full binder workflow pipeline.

Tests the complete flow:
  1. Create a task → file written to ~/Vault/binder/#tasks/
  2. Update task status → file updated
  3. Generate feeds → JSON written to ~/uDos/shared/feeds/
  4. MCP server serves feeds → binder_feed tool returns correct data
  5. Cross-lane webhook → GitHub PR merge triggers task status change

These tests use temporary directories to avoid touching real data.
"""

import json
import os
import sys
import tempfile
from pathlib import Path
from datetime import date
from unittest.mock import patch

import pytest

# Add project root to path

from test_integration_other import *  # other
from test_integration_scheduler import *  # scheduler
from test_integration_mcp import *  # mcp
from test_integration_dashboard import *  # dashboard
from test_integration_events import *  # events
from test_integration_health import *  # health

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215818_test_integration.py