"""job_queue — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215837

"""
Job Queue Service for uHomeNest Media Processing

This module implements a priority-based job queue system for media processing tasks
including DVR recordings, post-processing, and cleanup operations.
"""

import heapq
import json
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from uhome_server.config import get_logger


from job_queue_other import *  # other
from job_queue_health import *  # health
from job_queue_process import *  # process

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215837_job_queue.py