"""health module — extracted from rules_engine.py"""
# Auto-generated by file-splitter on 20260618_215450

"""
Advanced Rules Engine for uHOME

This module implements a comprehensive rules engine with support for:
- Multiple rule types (DVR, automation, lifecycle)
- Complex condition evaluation
- Advanced scheduling
- Conflict resolution
- Rule lifecycle management
- Performance optimization
"""

import heapq
import json
import re
import threading
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union
from pydantic import BaseModel, validator

from uhome_server.config import get_logger


    
    def get_engine_status(self) -> Dict[str, Any]:
        """Get current engine status."""
        with self._lock:
            return {
                'rules_count': len(self.rules),
                'active_rules': sum(1 for r in self.rules.values() if r.enabled),
                'schedule_count': len(self.schedule),
                'upcoming_executions': sum(1 for e in self.schedule if e.status == 'scheduled'),
                'conflicts_detected': sum(1 for c in self.conflicts.values() if c.status == 'detected'),
                'conflicts_resolved': sum(1 for c in self.conflicts.values() if c.status == 'resolved'),
                'execution_history_count': len(self.execution_history),
                'initialized': self._initialized,
                'last_updated': datetime.now().isoformat()
            }
    
    def cleanup(self, max_history: int = 1000):
        """Clean up old execution history."""
        with self._lock:
            if len(self.execution_history) > max_history:
                self.execution_history = self.execution_history[-max_history:]
                if self.persistence_path:
                    self._save_data()
                _log.info(f"Cleaned up execution history, kept {len(self.execution_history)} entries")


# ============================================================================
# Global Engine Instance
# ============================================================================

_engine: Optional[RuleEngine] = None


def get_rules_engine(persistence_path: Optional[Path] = None) -> RuleEngine:
    """Get the global rules engine instance."""
    global _engine
    if _engine is None:
        _engine = RuleEngine(persistence_path=persistence_path)
    return _engine


# ============================================================================
# Rule DSL Parser (Basic Implementation)
# ============================================================================

class RuleDSLParser:
    """Parser for uHOME Rule DSL."""
    
    def __init__(self):
        self.patterns = {
            'rule_name': r'rule\s+"([^"]+)"\s*\{',
            'field': r'(\w+)\s*:\s*([^,}\s]+)',
            'array': r'(\w+)\s*:\s*\[([^\]]+)\]',
            'string': r'"([^"]+)"',
            'number': r'(\d+(\.\d+)?)',
            'boolean': r'(true|false)'
        }
    
    def parse(self, dsl_text: str) -> Dict[str, Any]:
        """Parse DSL text into rule definition."""
        rule_def = {}
        current_section = None
        
        lines = [line.strip() for line in dsl_text.split('\n') if line.strip()]
        
        for line in lines:
            # Skip comments
            if line.startswith('#') or line.startswith('//'):
                continue
                
            # Rule definition start
            if line.startswith('rule'):
                match = re.match(self.patterns['rule_name'], line)
                if match:
                    rule_def['rule_name'] = match.group(1)
                    rule_def['rule_type'] = 'time-based'  # default
                    continue
            
            # Section start
            if line.endswith('{'):
                section_name = line[:-1].strip()
                current_section = section_name
                rule_def[current_section] = {}
                continue
            
            # Section end
            if line == '}':
                current_section = None
                continue
            
            # Field assignment
            if current_section and ':' in line:
                field_match = re.match(self.patterns['field'], line)
                if field_match:
                    field_name = field_match.group(1)
                    field_value = field_match.group(2)
                    
                    # Clean up value
                    field_value = field_value.strip('"')
                    if field_value.lower() == 'true':
                        field_value = True
                    elif field_value.lower() == 'false':
                        field_value = False
                    elif field_value.isdigit():
                        field_value = int(field_value)
                    
                    rule_def[current_section][field_name] = field_value
        
        return rule_def


def create_rule_from_dsl(dsl_text: str) -> Optional[Rule]:
    """Create a rule from DSL text."""
    parser = RuleDSLParser()
    rule_def = parser.parse(dsl_text)
    
    if not rule_def:
        return None
    
    # Convert to proper rule format
    rule_data = {
        'rule_name': rule_def.get('rule_name', 'Unnamed Rule'),
        'rule_type': rule_def.get('rule_type', RuleType.TIME_BASED.value),
        'priority': rule_def.get('priority', PriorityLevel.MEDIUM.value),
        'enabled': rule_def.get('enabled', True),
        'description': rule_def.get('description', '')
    }
    
    # Add type-specific fields
    if rule_data['rule_type'] == RuleType.TIME_BASED.value:
        rule_data.update({
            'channel_id': rule_def.get('channel', {}).get('id', 'unknown'),
            'start_time': rule_def.get('time', {}).get('start', '18:00'),
            'end_time': rule_def.get('time', {}).get('end', '19:00'),
            'recurrence': rule_def.get('recurrence', RecurrencePattern.ONCE.value)
        })
    
    # Create the rule
    engine = get_rules_engine()
    return engine.create_rule(rule_data)

