"""rules_engine — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215450

"""
Advanced Rules Engine for uHOME

This module implements a comprehensive rules engine with support for:
- Multiple rule types (DVR, automation, lifecycle)
- Complex condition evaluation
- Advanced scheduling
- Conflict resolution
- Rule lifecycle management
- Performance optimization
"""

import heapq
import json
import re
import threading
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union
from pydantic import BaseModel, validator

from uhome_server.config import get_logger


from rules_engine_other import *  # other
from rules_engine_events import *  # events
from rules_engine_mission_control import *  # mission_control
from rules_engine_health import *  # health

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215450_rules_engine.py