# Auto-generated by LENS-Craft v1.0
# Source: /Users/fredbook/Code/uCode/programs/elite/src/
# 20 extractors generated


class EliteLensExtractor:

    def __init__(self, emu):
        """Initialize with a 6502 emulator instance.

        Args:
            emu: Emulator providing read_byte(addr), read_uint16(addr),
                 read_uint32(addr) in little-endian byte order.
        """
        self._emu = emu

    @property
    def src_ship_status(self) -> str:
        """0=docked, 1=in flight, 2=docking, 3=jumping"""
        val = self._emu.read_byte(0x222)
        labels = {
        0: "docked",
        1: "in_flight",
        2: "docking",
        3: "jumping"
        }
        return labels.get(val, "unknown")

    @property
    def src_ship_loc_x(self) -> str:
        """Current system X coordinate (16-bit)"""
        val = self._emu.read_byte(0x234)
        labels = {
        0: "off",
        1: "on"
        }
        return labels.get(val, "unknown")

    @property
    def src_ship_loc_y(self) -> str:
        """Current system Y coordinate (16-bit)"""
        val = self._emu.read_byte(0x236)
        labels = {
        0: "off",
        1: "on"
        }
        return labels.get(val, "unknown")

    @property
    def src_credits_lo(self) -> int:
        """Credit balance low byte (tenths of credit)"""
        return self._emu.read_byte(0x200)

    @property
    def src_credits_hi(self) -> int:
        """Credit balance high byte"""
        return self._emu.read_byte(0x201)

    @property
    def src_inventory_start(self) -> int:
        """12 commodity slots (1 byte each: tonnes)"""
        return self._emu.read_byte(0x240)

    @property
    def src_fuel(self) -> int:
        """Hyperspace fuel (0-70 light years)"""
        return self._emu.read_byte(0x24c)

    @property
    def src_ship_energy(self) -> int:
        """Energy banks (0-255)"""
        return self._emu.read_byte(0x250)

    @property
    def src_ship_shields(self) -> int:
        """Shield strength"""
        return self._emu.read_byte(0x251)

    @property
    def src_laser_temp(self) -> int:
        """Laser temperature"""
        return self._emu.read_byte(0x252)

    @property
    def src_missile_count(self) -> int:
        """Missiles remaining (0-4)"""
        return self._emu.read_byte(0x253)

    @property
    def src_government(self) -> int:
        """Government type (0-7)"""
        return self._emu.read_byte(0x270)

    @property
    def src_economy(self) -> int:
        """Economy type (0-7)"""
        return self._emu.read_byte(0x271)

    @property
    def src_tech_level(self) -> int:
        """Tech level (0-14)"""
        return self._emu.read_byte(0x272)

    @property
    def src_overheating(self) -> int:
        """overheating data label"""
        return self._emu.read_byte(0x1153)

    @property
    def src_commodity_table(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x119b)

    @property
    def src_ship_data_table(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x11a7)

    @property
    def src_planet_descriptions(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x11b1)

    @property
    def src_screen_buffer(self) -> int:
        """============================================================"""
        return self._emu.read_byte(0x11b9)

    @property
    def src_screen_buffer(self) -> dict:
        """ScreenBuffer data structure"""
        return {
        }


    def capture_all(self) -> dict:
        """Capture all known state in a single snapshot."""
        return {
            "src_ship_status": self.src_ship_status,
            "src_ship_loc_x": self.src_ship_loc_x,
            "src_ship_loc_y": self.src_ship_loc_y,
            "src_credits_lo": self.src_credits_lo,
            "src_credits_hi": self.src_credits_hi,
            "src_inventory_start": self.src_inventory_start,
            "src_fuel": self.src_fuel,
            "src_ship_energy": self.src_ship_energy,
            "src_ship_shields": self.src_ship_shields,
            "src_laser_temp": self.src_laser_temp,
            "src_missile_count": self.src_missile_count,
            "src_government": self.src_government,
            "src_economy": self.src_economy,
            "src_tech_level": self.src_tech_level,
            "src_overheating": self.src_overheating,
            "src_commodity_table": self.src_commodity_table,
            "src_ship_data_table": self.src_ship_data_table,
            "src_planet_descriptions": self.src_planet_descriptions,
            "src_screen_buffer": self.src_screen_buffer,
            "src_screen_buffer": self.src_screen_buffer
        }

