"""bridge — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215823

"""
GameToTeletextBridge — Convert game output to teletext grid format

This module provides the bridge between game output (ANSI/ASCII)
and the CeefaxThinUI teletext grid format (40x25 characters).

Features:
    - ANSI escape sequence parsing and colour mapping
    - ASCII art to teletext grid conversion
    - 40x25 character grid with per-cell colour attributes
    - SKIN style application to teletext output
    - Export to CeefaxThinUI format, HTML, and PNG
"""

from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any
from enum import Enum
import re



from bridge_other import *  # other
from bridge_ceefax import *  # ceefax
from bridge_map import *  # map
from bridge_bridge import *  # bridge
from bridge_process import *  # process

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215823_bridge.py