"""ceefax_cli — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215546

#!/usr/bin/env python3
"""
CeefaxThinUI CLI — Command-line interface for teletext rendering and export

Usage:
  ucode ceefax [COMMAND] [OPTIONS]

Commands:
  parse       Parse text/ANSI file to teletext grid
  render      Render teletext grid in terminal (ANSI output)
  export      Export teletext grid to HTML, ANSI, or JSON
  serve       Start ThinUI API server with Ceefax endpoints
  app         Run the CEETEX Textual teletext app
  feed        Subscribe to feed channels for live teletext updates
  spool       Import/export teletext page collections
  mcp         Send MCP remote control commands to Ceefax
  vdu         Bridge BBC BASIC VDU output to teletext pages
  help        Show help for a command

Examples:
  ucode ceefax parse mygrid.txt
  ucode ceefax render mygrid.txt
  ucode ceefax export mygrid.txt --format html
  ucode ceefax export mygrid.txt --format ansi
  ucode ceefax serve --port 8001
  ucode ceefax app
  ucode ceefax feed subscribe news 101
  ucode ceefax feed poll
  ucode ceefax spool save 101 --title "News"
  ucode ceefax spool export mypages
  ucode ceefax mcp send PAGE 101
  ucode ceefax mcp send NEXT
  ucode ceefax vdu connect
  ucode ceefax vdu write "Hello from BBC BASIC!"
"""

import sys
import os
import json
import argparse
from pathlib import Path
from typing import Optional

# Add core_py to path

from ceefax_cli_ceefax import *  # ceefax
from ceefax_cli_other import *  # other
from ceefax_cli_mcp import *  # mcp

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215546_ceefax_cli.py