"""mcp module — extracted from ceefax_cli.py"""
# Auto-generated by file-splitter on 20260618_215546

#!/usr/bin/env python3
"""
CeefaxThinUI CLI — Command-line interface for teletext rendering and export

Usage:
  ucode ceefax [COMMAND] [OPTIONS]

Commands:
  parse       Parse text/ANSI file to teletext grid
  render      Render teletext grid in terminal (ANSI output)
  export      Export teletext grid to HTML, ANSI, or JSON
  serve       Start ThinUI API server with Ceefax endpoints
  app         Run the CEETEX Textual teletext app
  feed        Subscribe to feed channels for live teletext updates
  spool       Import/export teletext page collections
  mcp         Send MCP remote control commands to Ceefax
  vdu         Bridge BBC BASIC VDU output to teletext pages
  help        Show help for a command

Examples:
  ucode ceefax parse mygrid.txt
  ucode ceefax render mygrid.txt
  ucode ceefax export mygrid.txt --format html
  ucode ceefax export mygrid.txt --format ansi
  ucode ceefax serve --port 8001
  ucode ceefax app
  ucode ceefax feed subscribe news 101
  ucode ceefax feed poll
  ucode ceefax spool save 101 --title "News"
  ucode ceefax spool export mypages
  ucode ceefax mcp send PAGE 101
  ucode ceefax mcp send NEXT
  ucode ceefax vdu connect
  ucode ceefax vdu write "Hello from BBC BASIC!"
"""

import sys
import os
import json
import argparse
from pathlib import Path
from typing import Optional

# Add core_py to path


    def _command_mcp(self, args):
        """Send MCP remote control commands to Ceefax.

        Usage: ucode ceefax mcp <subcommand> [OPTIONS]

        Subcommands:
          send COMMAND [ARGS]      Send an MCP command
          status                   Show current MCP state
          history                  Show command history
          clear                    Clear pending commands and responses

        Commands:
          NEXT       Next page
          PREV       Previous page
          SUB        Toggle subtitle
          INDEX      Go to index (page 100)
          REVEAL     Toggle reveal
          PAGE <n>   Go to specific page
          HOLD       Toggle hold
          SIZE       Toggle double height
          MIX        Toggle mix mode
          LIST       List pages
          STATUS     Show status
        """
        if len(args) < 1:
            print("Usage: ucode ceefax mcp <subcommand> [OPTIONS]")
            print("Subcommands: send, status, history, clear")
            return

        from core_py.ceefax.mcp_protocol import create_ceefax_mcp
        mcp = create_ceefax_mcp()

        subcommand = args[0]
        sub_args = args[1:]

        if subcommand == "send":
            if len(sub_args) < 1:
                print("Usage: ucode ceefax mcp send COMMAND [ARGS]")
                print("Commands: NEXT, PREV, SUB, INDEX, REVEAL, PAGE <n>, HOLD, SIZE, MIX, LIST, STATUS")
                return
            cmd_str = " ".join(sub_args)
            cmd = mcp.queue_command(cmd_str, source="cli")
            response = mcp.process_command(cmd)
            if response:
                if response.success:
                    print(f"✅ {response.result}")
                else:
                    print(f"❌ {response.error}")
            else:
                print(f"✅ Command queued: {cmd_str}")

        elif subcommand == "status":
            state = mcp.get_state()
            print("Ceefax MCP State:")
            print(f"  Current page:  {state['current_page']}")
            print(f"  Subtitle:      {'on' if state['subtitle'] else 'off'}")
            print(f"  Reveal:        {'on' if state['reveal'] else 'off'}")
            print(f"  Hold:          {'on' if state['hold'] else 'off'}")
            print(f"  Double height: {'on' if state['double_height'] else 'off'}")
            print(f"  Mix mode:      {'on' if state['mix_mode'] else 'off'}")
            print(f"  Pending cmds:  {state['pending_commands']}")
            print(f"  History:       {state['command_history']} commands")

        elif subcommand == "history":
            history = mcp.get_history(limit=20)
            if not history:
                print("No command history")
                return
            print("Command history:")
            for h in history:
                print(f"  {h['command']} ({h['source']})")

        elif subcommand == "clear":
            mcp.clear_commands()
            mcp.clear_responses()
            print("✅ Cleared pending commands and responses")

        else:
            print(f"Unknown mcp subcommand: {subcommand}")

    # ── VDU Commands ───────────────────────────────────────────────

    def _command_vdu(self, args):
        """Bridge BBC BASIC VDU output to teletext pages.

        Usage: ucode ceefax vdu <subcommand> [OPTIONS]

        Subcommands:
          connect                  Connect to VDU driver (simulated)
          write TEXT               Write text to VDU page
          page [NUMBER]            Get/set current VDU page number
          flush                    Flush buffered text to grid
          clear                    Clear VDU page
          grid                     Show current grid as ANSI
          html                     Export current grid as HTML
          pages                    List VDU pages
          title TEXT [PAGE]        Set page title
          subtitle TEXT [PAGE]     Set page subtitle
        """
        if len(args) < 1:
            print("Usage: ucode ceefax vdu <subcommand> [OPTIONS]")
            print("Subcommands: connect, write, page, flush, clear, grid, html, pages, title, subtitle")
            return

        from core_py.ceefax.vdu_bridge import create_vdu_bridge
        vdu = create_vdu_bridge()

        subcommand = args[0]
        sub_args = args[1:]

        if subcommand == "connect":
            print("✅ VDU bridge initialized (page 500)")
            print("   Use 'vdu write TEXT' to send text")
            print("   Use 'vdu page NUMBER' to change page")

        elif subcommand == "write":
            if len(sub_args) < 1:
                print("Usage: ucode ceefax vdu write TEXT")
                return
            text = " ".join(sub_args)
            vdu.write(text)
            vdu.flush()
            print(f"✅ Wrote: {text[:60]}{'...' if len(text) > 60 else ''}")

        elif subcommand == "page":
            if sub_args:
                vdu.set_page_number(int(sub_args[0]))
            print(f"Current VDU page: {vdu.get_page_number()}")

        elif subcommand == "flush":
            grid = vdu.flush()
            if grid:
                print("✅ Flushed buffer to grid")
            else:
                print("No buffered text to flush")

        elif subcommand == "clear":
            vdu.clear()
            print("✅ VDU page cleared")

        elif subcommand == "grid":
            ansi = vdu.to_ansi()
            print(ansi)

        elif subcommand == "html":
            html = vdu.to_html()
            print(html)

        elif subcommand == "pages":
            pages = vdu.list_pages()
            if not pages:
                print("No VDU pages")
                return
            print("VDU pages:")
            for p in pages:
                print(f"  Page {p['page_number']}: {p['title']} ({p['update_count']} updates)")

        elif subcommand == "title":
            if len(sub_args) < 1:
                print("Usage: ucode ceefax vdu title TEXT [PAGE]")
                return
            title = sub_args[0]
            page = int(sub_args[1]) if len(sub_args) > 1 else None
            vdu.set_title(title, page)
            print(f"✅ Title set: {title}")

        elif subcommand == "subtitle":
            if len(sub_args) < 1:
                print("Usage: ucode ceefax vdu subtitle TEXT [PAGE]")
                return
            subtitle = sub_args[0]
            page = int(sub_args[1]) if len(sub_args) > 1 else None
            vdu.set_subtitle(subtitle, page)
            print(f"✅ Subtitle set: {subtitle}")

        else:
            print(f"Unknown vdu subcommand: {subcommand}")


def main():
    """Main entry point for ceefax CLI"""
    cli = CeefaxCLI()
    cli.main(sys.argv[1:])



if __name__ == "__main__":
    main()

