"""test_snack_container — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215616

"""
Tests for the uCode1 Snack Container Format (snack.yaml, loader, registry, snackpack).
"""

import json
import os
import sys
import tempfile
from pathlib import Path

import pytest
import yaml

# Add parent to path for imports

from test_snack_container_other import *  # other
from test_snack_container_snacks import *  # snacks
from test_snack_container_mcp import *  # mcp

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215616_test_snack_container.py