"""grid_editor — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215758

"""
Grid Editor — Interactive Grid Painting and Editing

Provides cursor-based grid editing with:
- Cursor movement and painting
- Flood fill and selection
- Copy/paste regions
- Multi-layer editing support
- Undo/redo via EditHistory
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple

from ..grid.models import Grid, GridCell, Coordinate, GridRegion, GridSize
from ..grid.layers import GridLayer, GridStack, LayerType
from .history import EditHistory
from .palette import CharacterPalette, SlotEntry



from .grid_editor_other import *  # other

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215758_grid_editor.py