"""acs_memory_map — slim entry point (modules split by file-splitter)"""
# Auto-generated by file-splitter on 20260618_215806

"""
ACS Memory Map — Known Memory Addresses for Adventure Construction Set

This module documents the memory layout of Adventure Construction Set (ACS)
games, providing known addresses for tile grids, room data, inventory,
creatures, story flags, and player statistics.

The ACS memory map is based on the Apple II version of Adventure Construction
Set by Stuart Smith (Electronic Arts, 1984). Memory addresses are mapped
relative to the game's loaded memory space.

Memory Layout:
    0x0000 - 0x00FF: Zero page / system variables
    0x0100 - 0x01FF: Stack
    0x0200 - 0x02FF: Player stats block
    0x0300 - 0x03FF: Current room data
    0x0400 - 0x04FF: Tile grid (15x15 = 225 bytes)
    0x0500 - 0x05FF: Creature data block
    0x0600 - 0x06FF: Inventory data block
    0x0700 - 0x07FF: Story flags
    0x0800 - 0x0FFF: Room descriptions (string data)
    0x1000 - 0x1FFF: Tile definitions
    0x2000 - 0x2FFF: Creature definitions
    0x3000 - 0x3FFF: Item definitions
    0x4000 - 0x4FFF: Room definitions
    0x5000 - 0x5FFF: Message strings
    0x6000 - 0x6FFF: Game logic / scripts
    0x7000 - 0x7FFF: Extended data
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple


# ── Memory Region Definitions ──────────────────────────────────────


from acs_memory_map_other import *  # other
from acs_memory_map_map import *  # map

# Original file backed up to:
#   /Users/fredbook/.snackbar/backups/file-splitter/20260618_215806_acs_memory_map.py